### ISSUE TITLE
Oportunidade de ajuda

### ISSUE THREAD

**Issue by LucasdfRocha** [Mateus7G/crp-iframe-player#119]
Ola, sou novo nessa área  tech, e gostaria de pedir pra poder ajudar você no desenvolvimento nesse script, ja que eu gostaria de aprender um pouco mais de javascript, Eu nao sei praticamente nada de JS mas estou disposto a aprender.
 Entrei recentemente em uma facul de ciencia da comp e vi esse teu script como uma oportunidade! Qualquer coisa, entra no meu perfil e me manda uma mensagem por favor!

**Comment by Andrey0800770** [comment]
Eu recomendo que você faça um fork desse repo, pois o @Mateus7G parece que não vai mais mecher nesse repositorio.
