### ISSUE TITLE
Erro em alguns episódios

### ISSUE THREAD

**Issue by K4nek0** [Mateus7G/crp-iframe-player#12]
Os episódios 88, 89 e 90 de Naruto Shippuden (International Dubs) não estão funcionando. Verifiquei todos os outros animes da categoria International dubs, e todos estão funcionando corretamente. Agradeço pela minha primeira solicitação corrigida e estou no aguardo de mais esta.

**Comment by Mateus7G** [comment]
Infelizmente dessa vez não é um erro da extensão: não tem como corrigir. :/

Acontece que se você tirar a extensão vai ver que esses 3 episódios não estão com trailer, e por isso não da para pegar as informações do episódio e substituir o player original (vilos).
Talvez por serem eps de 2008 a cr esqueceu de colocar os trailers mas não tenho certeza se você entrar em contato com o suporte é possivel que eles adicionem trailers.

**Comment by Andrey0800770** [comment]
Aqui está funcionando perfeitamente

![Screenshot_20210418-110149](https://user-images.githubusercontent.com/66447173/115148378-a6f95100-a035-11eb-8ae4-f559f10d6032.png)
![Screenshot_20210418-110226](https://user-images.githubusercontent.com/66447173/115148383-ab256e80-a035-11eb-81a0-6cea426ff75a.png)
![Screenshot_20210418-110119](https://user-images.githubusercontent.com/66447173/115148388-b37da980-a035-11eb-9357-80f556ed28e3.png)

**Comment by K4nek0** [comment]
Solicitei

Em dom., 18 de abr. de 2021 às 09:35, _Mateus7G ***@***.***>
escreveu:

**Comment by railanbarbosa** [comment]
episodio 25 de Durarara! da pra assistir mas n pra baixar

https://imgur.com/ufFpNAP

**Comment by Mateus7G** [comment]
@railanbarbosa nota: este problema não tem relação com o dessa issue.
no seu caso o ep 25 de Durarara não possui as 5 resoluções (1080p, 720p, 480p, 360p e 240p) e por isso não estava pegando pra download, o problema foi **"corrigido"** na f2589dcf09531ca680bc9953b21615b11768ab23 mas as resoluções 360p e 240p **continuam indisponíveis** pois não estão sendo mandadas pela cr além do que provavelmente os **nomes das resoluções na extensão estão incorretos** (motivo: por alguma razão este video em especifico ta com as qualidades quebradas e faltando - veja a imagem abaixo sem a extensão)

![image](https://user-images.githubusercontent.com/13335925/115899725-7baba300-a435-11eb-9baf-bbb8983cf875.png)
