### ISSUE TITLE
Solução temporaria usando a API do Kamyroll

### ISSUE THREAD

**Issue by Dev4Mod** [Mateus7G/crp-iframe-player#127]
[aqui](https://github.com/Dev4Mod/crp-iframe-player) uma solução temporaria usando a API do Kamyroll, algumas coisas não funciona ex: força mp4 e download, webvideocaster.
Apenas a extensão para o chrome foi adaptada.

**Comment by Pedro1Developer** [comment]
Booooa, isso vai funcionar permanente?

**Comment by Dev4Mod** [comment]
Não sei. Como usa uma API pode ser que pare de funcionar

**Comment by Aostaaa** [comment]
que isso, logo no dia de lancamento dos anime da primeira temporada de 2023. Muito obrigado pelo trabalho mano

**Comment by Aostaaa** [comment]
Po mano, funcionou apenas 1 vez e depois (Seu video iniciara em instantes (^-^)
Aguardando dados da stream..) so fica nessa, alguma ideia doq possa ser?

**Comment by Dev4Mod** [comment]
As vezes essa API fica caindo dando um erro 502. O única solução é esperar que retorne novamente. Como eu havia dito, é bem provável que isso aconteça já que é uma API de terceiros.

**Comment by Pedro1Developer** [comment]
tendi, essa é a unica forma?

**Comment by Pedro1Developer** [comment]
ja parou de funfar

**Comment by Dev4Mod** [comment]
Testei aqui e já está funcionando novamente

**Comment by gabeetto** [comment]
alguien me puede explicar como usar la api????

**Comment by Pedro1Developer** [comment]
Erro ao carregar o vídeo! (>﹏<)
Os cookies [estão desativados]!
O que isso? pra usar a app é só ativar a extensão né, funcionou agora

**Comment by TheDarkZapdos** [comment]
a api atualizou e mudou o POST pra GET 
eu vi isso no discord deles e eles falaram pra avisar que o POST não ta mais funcionando

**Comment by DARLINGzt** [comment]
> 

Manda o link do Discord deles por favor

**Comment by TheDarkZapdos** [comment]
https://discord.com/invite/g6JzYbh

**Comment by DARLINGzt** [comment]
> 

Valeu, agora só não sei como usar

**Comment by TheDarkZapdos** [comment]
Eles tem um app pro celular e pro Pc e tem como colocar os EP em pt br

**Comment by DARLINGzt** [comment]
> 

Caraca, poderia me enviar o app por favor?

**Comment by TheDarkZapdos** [comment]
Pra qual dispositivo

**Comment by DARLINGzt** [comment]
> 

Você consegue mandar o link?

**Comment by TheDarkZapdos** [comment]
Celular: https://github.com/saikou-app/saikou/releases/download/v1.2.0.23/Saikou-1.2.0.23.apk
Pra celular eu fiz um tutorial simples: https://youtube.com/shorts/pCe-BYWy5dc?feature=share

Pc: https://github.com/kamyroll/Kamyroll-Tauri/releases/download/v1.0.5-beta%2B6c599b3/Kamyroll_1.0.5_x64_en-US.msi no Pc quando você vai no episódio vai ter um negócio no player escrito ja-Jp e tem como mudar para ja-Jp Pt-br pra deixar em português

**Comment by TheDarkZapdos** [comment]
Se o de Pc não der pra entender me fala que eu explico melhor

**Comment by DARLINGzt** [comment]
> 

Valeu mano vc é um anjo

**Comment by DARLINGzt** [comment]
> 

Precisa não, eu não sou de PC

**Comment by TheDarkZapdos** [comment]
👍

**Comment by ErikGX21** [comment]
> Móvil: https://github.com/saikou-app/saikou/releases/download/v1.2.0.23/Saikou-1.2.0.23.apk Para móvil hice un tutorial sencillo: [https://youtube.com/shorts /pCe-BYWy5dc?feature=compartir](https://youtube.com/shorts/pCe-BYWy5dc?feature=share)
> 
> PC: https://github.com/kamyroll/Kamyroll-Tauri/releases/download/v1.0.5-beta%2B6c599b3/Kamyroll_1.0.5_x64_en-US.msi en la PC cuando vayas al episodio habrá algo escrito en el reproductor ja-Jp y hay una forma de cambiarlo a ja-Jp Pt-br para dejarlo en portugués

Puedes hacer un tutorial para el de PC?
Você pode fazer um tutorial para o PC?

**Comment by TheDarkZapdos** [comment]
Eu acabei de desligar o PC mas eu posso tentar explicar

**Comment by TheDarkZapdos** [comment]
Quando você escolher um episódio de algum anime pra assistir vai ter uma engrenagem e nessa engrenagem você pode mudar a legenda para seu idioma

**Comment by TheDarkZapdos** [comment]
Isso é no player do episódio

**Comment by Dev4Mod** [comment]
Eu vou  atualiza a mudança que teve na API hj a noite.

**Comment by flixmu** [comment]
Sometime kamyroll website down

**Comment by peg4sus21** [comment]
> Erro ao carregar o vídeo! (>﹏<) Os cookies [estão desativados]! O que isso? pra usar a app é só ativar a extensão né, funcionou agora

Como fez para funcionar? o meu ainda esta com este problema.

**Comment by peg4sus21** [comment]
> a api atualizou e mudou o POST pra GET eu vi isso no discord deles e eles falaram pra avisar que o POST não ta mais funcionando

como posso mudar de POST para GET?

**Comment by Dev4Mod** [comment]
> > a api atualizou e mudou o POST pra GET eu vi isso no discord deles e eles falaram pra avisar que o POST não ta mais funcionando
> 
> como posso mudar de POST para GET?

Paciência jovem, já será atualizado..

**Comment by Dev4Mod** [comment]
[Atualização aqui](https://github.com/Dev4Mod/crp-iframe-player/releases/tag/1.4.0), prontinho funcionando novamente.

**Comment by DARLINGzt** [comment]
Valeu ADM, você é demais

**Comment by DARLINGzt** [comment]
Mano o meu parou de funcionar, só fica carregando

**Comment by flixmu** [comment]
> Mano o meu parou de funcionar, só fica carregando

https://github.com/Mateus7G/crp-iframe-player/issues/127#issuecomment-1374695192

**Comment by DARLINGzt** [comment]
👍

**Comment by ALISONTS99** [comment]
Bom dia, e em relação a download e webvideocaster, é possivel arrumar tambem?

**Comment by DARLINGzt** [comment]
Para mim tá dando um erro 232011

**Comment by ErikGX21** [comment]
Também está me dando "Erro ao carregar o vídeo! (>﹏<)
Mais informações em Console.
Código: 232011"

**Comment by DARLINGzt** [comment]
Sim mano, logo agora que eu iria assistir kkkk

**Comment by ZaqueNTC** [comment]
Pra mim também, tanto na extensão do @Dev4Mod quanto no programa da Kamyroll, que acho que ele está usando a mesma api da Kamyroll. Tava funcionando normal até umas 20h da noite, ai do nada parou.   

Na extensão fica dando esse erro código 232011 ou fica carregando eternamente na tela "Seu video iniciara em instantes (^-^)
Aguardando dados da stream..". E no Kamyroll fica carregando eternamente, sem dar erro.

**Comment by Dev4Mod** [comment]
Já corrigi o problema, houve umas mudanças na crunchyroll que afetou até o kamyroll mas já foi resolvido. Baixei a versão mais recente no repositório.

**Comment by Dev4Mod** [comment]
Estou fechando esse issue. Caso tenha problema com a extensão, favor abrir uma issue no repositório que está sendo feito as atualizações

**Comment by DARLINGzt** [comment]
Parece está funcionando normalmente até melhor que a última versão, se houver alguma erro eu reporto, e valeu ADM vc é demais

**Comment by peg4sus21** [comment]
Baixei a versão mais recente, mas esta carregando infinitamente, aguem sabe o que fazer?

**Comment by DARLINGzt** [comment]
O meu também, acho que é só espera que alguma hora ela volta!

**Comment by Dev4Mod** [comment]
API está indisponivel, [https://api.kamyroll.tech/](https://api.kamyroll.tech/)

**Comment by Pedro1Developer** [comment]
esse site nao abre de forma alguma

**Comment by Dev4Mod** [comment]
Exatamente, só quando ele voltar que a kamyroll vai retornar

**Comment by Pedro1Developer** [comment]
oh, até a kamyroll parou de funcionar?

**Comment by Dev4Mod** [comment]
Sim

**Comment by Dev4Mod** [comment]
Pessoal, mais uma correção de cors, alguns animes que não estava funcionando agora deve estar normal.
[Atualização](https://github.com/Dev4Mod/crp-iframe-player/releases/lastest)

**Comment by valenfile** [comment]
É uma pena que a extensão ainda não funciona 😥

**Comment by valenfile** [comment]
Como me sinto feliz que a extensão esteja funcionando, muito obrigado 🥳🥳

**Comment by valenfile** [comment]
parou de novo 😥

**Comment by Dev4Mod** [comment]
Mais uma correção. o Crunchyroll esta chato ultimamente em relação aos cors
[Atualização](https://github.com/Dev4Mod/crp-iframe-player/releases)

**Comment by flixmu** [comment]
> Mais uma correção. o Crunchyroll esta chato ultimamente em relação aos cors [Atualização](https://github.com/Dev4Mod/crp-iframe-player/releases/lastest)

yes very annoying crunchyroll always update cors, I made a scrap website directly from crunchyroll sometimes encounter problems with cors

while maybe you can use this website, but it doesn't guarantee it will last long, and some videos are blocked by cors so they can't be played

http://flixapi.epizy.com/

**Comment by Pedro1Developer** [comment]
nao funciona ainda :D

**Comment by Pedro1Developer** [comment]
Tem como usar apk da kamyroll pra mobile?

**Comment by Dev4Mod** [comment]
> nao funciona ainda :D

Acabei de testar e está funcionando normal amigo

**Comment by Stindl** [comment]
Amigo, atualmente a extensão só vai te permitir assistir o anime? Pois tentei baixar mas não consigo, não sei se é um bug que só eu tenho.

Além disso, muito obrigado pelo seu trabalho!

**Comment by HackY12341** [comment]
> > nao funciona ainda :D
> 
> Acabei de testar y esta funcionando normal amigo
Olá amigo, não funciona mais para mim, você pode me ajudar ou estou fazendo algo errado? Eu só entendo .... Seu vídeo começará em instantes (^-^)
Aguardando dice da stream.... e muito obrigado pelo que fazem por nós.

**Comment by Pedro1Developer** [comment]
Alguém sabe se existe um apk pra mobile onde eu possa assistir os animes premium de graça?

**Comment by Pedro1Developer** [comment]
site da crunchyroll não carrega

**Comment by Pedro1Developer** [comment]
![image](https://user-images.githubusercontent.com/89951576/213485917-68b92ec4-ea9c-465a-a431-121f65630d41.png)
alguem me ajude

**Comment by K4nek0** [comment]
A Crunchyroll adicionou hoje no Player a opção de mudar os idiomas, teria como adicionar essa função no player do Iframe tbm? Caso não dê já não daria mais para assistir os títulos que estão dublados...

**Comment by Pedro1Developer** [comment]
> A Crunchyroll adicionou hoje no Player a opção de mudar os idiomas, teria como adicionar essa função no player do Iframe tbm? Caso não dê já não daria mais para assistir os títulos que estão dublados...

essa função só existe pra quem é premium?

**Comment by Pedro1Developer** [comment]
> Alguém sabe se existe um apk pra mobile onde eu possa assistir os animes premium de graça?

ALGUÉM PODE ME RESPONDER SOBRE ISSO??

**Comment by K4nek0** [comment]
> > A Crunchyroll adicionou hoje no Player a opção de mudar os idiomas, teria como adicionar essa função no player do Iframe tbm? Caso não dê já não daria mais para assistir os títulos que estão dublados...
> 
> essa função só existe pra quem é premium?

É pq essa função de mudar a opção de idioma, é no próprio player da CR, o IFrame usa outro player que não tem essa função. Mas acredito que se vc não for premium ele não libera as outras opções no player para você selecionar.

**Comment by Dev4Mod** [comment]
> site da crunchyroll não carrega

Testei está funcionando normalmente aqui

**Comment by AntonyRairon** [comment]
> Testei está funcionando normalmente aqui

Aqui tbm esta funcionando normalmente, mas não são todos os animes que a API Kamyroll funciona, um exemplo é Bleach que nem no app deles (Kamyroll) não encontra/reproduz 
![image](https://user-images.githubusercontent.com/53920499/213619158-74f74b82-11f9-47a5-a4f4-2228d66f0420.png)
Basicamente todos os animes que não encontrei no app deles, tbm não funcionou com a extensão no site.

**Comment by Snacky19** [comment]
Fala irmão, você poderia achar um jeito de anular a coisa que aparece quando você tenta abrir um anime dublado pois com essa aba não da pra dar player no anime 
![image](https://user-images.githubusercontent.com/123278818/213895652-a3064198-643e-49cb-8979-1af78ab5c405.png)

**Comment by lucas10cs** [comment]
pra mim a extenção e o app do kamyroll pararam de funcionar
alguem sabe se tem como solucionar?

**Comment by PJ-The-Realest** [comment]
> pra mim a extenção e o app do kamyroll pararam de funcionar alguem sabe se tem como solucionar?

Não. Ela caiu, por causa de direito autoral.

**Comment by Dev4Mod** [comment]
E assim chega ao fim
