### ISSUE TITLE
Extensão

### ISSUE THREAD

**Issue by Marco9289** [Mateus7G/crp-iframe-player#13]
Oi Mateus tudo bem uso a extensão Crunchyroll iFrame Player a bastante tempo estou muito satisfeito gostaria de saber se tem alguma possibilidade de você criar uma extensão do serviço de streaming de animes Funimation usando essa extensão como base obrigado

**Comment by Mateus7G** [comment]
opa marco tudo bom
eu respondi essa pergunta num comentário, infelizmente pra funimation nn vai ter como já que eles não tem nem trailers nos eps de assinantes... 
> "eu dei uma analisada e a unica coisa que da pra fazer é uma extensão pros eps publicos pra tirar os anuncios e mostrar o botão de download, mas diferente do sistema da crunchyroll, os videos que precisam de assinatura são protegidos por autenticação, se pá que o da funimation nn vai ter como não :/"
**respondido em:** https://github.com/Mateus7G/crp-iframe-player/commit/c201dc2e2639ea5e99e1dc663188809057ea9d8e#commitcomment-49664298

**Comment by Marco9289** [comment]
> opa marco tudo bom
> eu respondi essa pergunta num comentário, infelizmente pra funimation nn vai ter como já que eles não tem nem trailers nos eps de assinantes. o deles eh um sistema parecido porém não é totalmente igual...
> 
> > "eu dei uma analisada e a unica coisa que da pra fazer é uma extensão pros eps publicos pra tirar os anuncios e mostrar o botão de download, mas diferente do sistema da crunchyroll, os videos que precisam de assinatura são protegidos por autenticação, se pá que o da funimation nn vai ter como não :/"
> > **respondido em:** [c201dc2#commitcomment-49664298](https://github.com/Mateus7G/crp-iframe-player/commit/c201dc2e2639ea5e99e1dc663188809057ea9d8e#commitcomment-49664298)

Opa Matheus beleza tá tranquilo entendo a situação e obrigado por resgatar a extensão depois que o itallolegal descontinuou o Projeto open-source, não sei qual o motivo levou ele descontinuar o projeto mas enfim obrigado por tudo abraços
