### ISSUE TITLE
Funcionando apenas nos episódios premium

### ISSUE THREAD

**Issue by crackerbad** [Mateus7G/crp-iframe-player#14]
Aqui reparei que ele só esta funcionando para os epsódios premiuns, os episódios gratuitos o player fica carregando procurando as informações e nada.

**Comment by Mateus7G** [comment]
testei aqui e a extensão está normal... poderia informar qual episodio se trata?
(verifique também se vc está utilizando a ultima versão da extensão)

**Comment by Mateus7G** [comment]
devido a inatividade vou fechar essa issue, creio que por enquanto não há problemas
