### ISSUE TITLE
Auto Fullscreen não funcionando

### ISSUE THREAD

**Issue by NedcloarBR** [Mateus7G/crp-iframe-player#15]
Então é bem oque o titulo da issue diz o auto fullscreen do next_up não está funcionando quando começa a tocar o proximo ep e o contador de segundos para executar o next_up no popup.html tmb não salva o valor de quando deve executar a ação
assisto deitado na cama dai ter que toda hora ficar levantando pra colocar em fullscreen é complicado

**Comment by Mateus7G** [comment]
olá @NedcloarBR e obrigado pelo contato.
eu desativei o fullscreen na 154150eb81e9f4de7c1aac6452702c2a60d8e78b pq não estava funcionando (se tentar rodar o player localmente vai ver que ao descomentar a [L233](https://github.com/Mateus7G/crp-iframe-player/blob/154150eb81e9f4de7c1aac6452702c2a60d8e78b/assets/js/player.js#L233) o player não entra em fullscreen, e ainda buga o botao de fullscreen) por causa de uma [feature de segurança](https://stackoverflow.com/a/14244427) do chrome. diferente da netflix/yt que faz isso **nativamente** já q o site deles foi desenvolvido pensano em ser uma [SPA](https://pt.wikipedia.org/wiki/Aplicativo_de_página_única), no crunchyroll cada video q vc assiste é um site diferente que é carregado, e por isso não da pra fazer o next_up com fullscreen (uma alternativa seria fazer a propria extensao transformar o site inteiro numa spa meia boca, é possivel mas é bem trabalhoso p causa dos comentários etc... ainda to vendo oq da pra fazer)
sugiro utilizar o teamviewer no celular como um controle remoto caso nao queira sair da cama pra botar em fullscreen

quanto ao contador, vc pode me dizer se tem algum log de **Error** no `chrome://extensions`? (se o botao Error não aparecer quer dizer que não tem) aqui pra mim ta salvando normal imediatamente após alterar...

**Comment by NedcloarBR** [comment]
Então eu estava pesquisando sobre o auto fullscreen mas não tinha achado sobre isso eu vou começar a usar mais o remote desktop pra colocar em fullscreen

quanto ao erro: 
```javascript
//TODO: check all ports (now hardcoded)
var ports = [6463, 6473];
var windowID;

function updatePresence(title) {
	var xhr = new XMLHttpRequest();
	xhr.withCredentials = true;
	xhr.open("POST", "http://localhost:3000/?data="+title);
	xhr.send();
}

function spoofHeader(details){	
	var headers = [ {name: "Content-Type", value: "application/json"} ];
	
	return { requestHeaders: headers };
}

function onTabUpdate(id, status, tab){
	console.log(tab)
	if(tab.url.startsWith("http://www.crunchyroll.com/*")) {
		if(status.status != "complete") return;
		chrome.tabs.query({ active: true }, function (tabs) {
			windowId = tab.windowId
			updatePresence(tabs[0].title.split(" - Assista na Crunchyroll")[0]);
		});
	}
}

function onTabClose(id, status, tab){
	console.log(status)
	if(status.windowId === windowId) {
			updatePresence("closed_tab");
			windowId = undefined
		}
}


chrome.webRequest.onBeforeSendHeaders.addListener(spoofHeader,  {urls: ["http://localhost:3000/*"]}, ["requestHeaders", "blocking"])
chrome.tabs.onUpdated.addListener(onTabUpdate);
chrome.tabs.onRemoved.addListener(onTabClose);
```

**Comment by Mateus7G** [comment]
bom realmente se esse erro é de outra extensão nn tem mta relação. eu iria dizer q talvez seja algo especifico do kiwi mas aparentemente vc esta usando o chrome desktop né? de vdd nao faço ideia do q houve.
bom vc ainda pode tentar abrir a modal da extensão e inspecionar elemento > Console > e botar esse codigo:

    chrome.storage.sync.set({'cooldown': 5}); // no lugar do 5, o tempo em segundos

depois que fechar e abrir a extensao os valores devem atualizar

![image](https://user-images.githubusercontent.com/13335925/117082428-a1c82180-ad18-11eb-9500-619055d9a060.png)

**Comment by NedcloarBR** [comment]
Então dei uma mudada nos códigos aqui de outras extensões que eu coloquei junto ao player e o começou a salvar o tempo!
pena que o auto fullscreen não é possível 😥 
mas tipo não teria como fazer uma simulação como se o usuário tivesse clicado no botão?
