### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by wall1n** [Mateus7G/crp-iframe-player#16]
Alguém sabe me dizer o motivo de não funcionar no meu PC ?
Ele carrega eternamente o video mas não abre, mesmo não sendo um video premium, o mais estranho é que no PC do amigo que me passou essa extensão funciona direitinho no Edge, mas aqui não.

![Screenshot (91)](https://user-images.githubusercontent.com/78543502/117885354-21f40700-b284-11eb-99df-a6a311643d98.png)
![Screenshot (93)](https://user-images.githubusercontent.com/78543502/117885359-23253400-b284-11eb-8fa7-b9411db2acf7.png)

**Comment by Mateus7G** [comment]
vai em um ep qualquer e abre as ferramentas de desenvolvedor na aba Console (ctrl + shift + i), d preferencia aumenta o tamanho pra caber mais coisa e manda print aqui

**Comment by wall1n** [comment]
Eu uso o Microsoft Edge, o estranho é que o amigo que me indicou essa extensão também usa o mesmo navegador, mas no dele funciona normalmente e mesmo aumentando o tamanho não funcionou, no console aparecem varios erros.

![Screenshot (94)](https://user-images.githubusercontent.com/78543502/117891306-0e00d300-b28d-11eb-80d2-c3e0438925bb.png)

![Screenshot (95)](https://user-images.githubusercontent.com/78543502/117891309-0f320000-b28d-11eb-9d41-8ae1acb33c12.png)

**Comment by wall1n** [comment]
Só vai até aqui.

Página inteira:
![Screenshot (96)](https://user-images.githubusercontent.com/78543502/117954294-4506d100-b2ed-11eb-85ac-8a8246bf7340.png)


Página cortada:
![Screenshot (97)](https://user-images.githubusercontent.com/78543502/117954300-4637fe00-b2ed-11eb-9671-b2884c35ccb2.png)

**Comment by Mateus7G** [comment]
cara por mais incrivel que pareça não deu erro nenhum...
tenta desativar o adblock na crunchyroll ou talvez alguma outra extensão que possa estar bloqueando (até pq essa extensão do cr remove o anuncio automaticamente), se não der certo tenta limpar o cache e por ultimo se nada resolver acho que só utilizando outro navegador (recomendo o opera gx, é bem rápido): se esse for o problema realmente não sei o que há de diferente entre o seu edge e o do seu amigo.

**Comment by wall1n** [comment]
Bom, valeu pela ajuda, o jeito foi trocar o navegador mesmo porque no Chrome e no Opera GX funcionou direitinho, mas o Edge não vai.
