### ISSUE TITLE
Histórico de episódios travado.

### ISSUE THREAD

**Issue by komisanwakomyushou** [Mateus7G/crp-iframe-player#18]
O título já é autoexplicativo, estou tendo problemas com o histórico de episódio do site. Assisto alguns eps e depois não aparecem no histórico ou mostram a barrinha laranja mostrando a ultima parte que parei. Talvez isso seja um recurso da própria extensão evitando banimento?

**Comment by Mateus7G** [comment]
O histórico de eps fica no lado do servidor (fica salvo **sua conta** do crunchyroll) e é automaticamente atualizado pelo player **deles**: o vilos.
pra nao ficar totalmente sem, o nosso jwplayer tem um sistema de histórico tbm, mas no lado do client (fica salvo no **navegador**): se vc sair de um ep vai voltar de onde parou.

Já a barrinha laranja ela vem preenchida do servidor, é possível alterar mas teria que mudar nao só o codigo do nosso player mas também da extensão em sí (todo mundo teria q baixar dnv) talvez qnd a extenção precisar de uma atualização eu aproveito e faço isso

**Comment by komisanwakomyushou** [comment]
> O histórico de eps fica no lado do servidor (fica salvo **sua conta** do crunchyroll) e é automaticamente atualizado pelo player **deles**: o vilos.
> pra nao ficar totalmente sem, o nosso jwplayer tem um sistema de histórico tbm, mas no lado do client (fica salvo no **navegador**): se vc sair de um ep vai voltar de onde parou.
> 
> Já a barrinha laranja ela vem preenchida do servidor, é possível alterar mas teria que mudar nao só o codigo do nosso player mas também da extensão em sí (todo mundo teria q baixar dnv) talvez qnd a extenção precisar de uma atualização eu aproveito e faço isso

Certo, agradeço imensamente se puder fazer isso. Obrigada ^-^
