### ISSUE TITLE
How to change hard_sub english subtitle to non subtitle video

### ISSUE THREAD

**Issue by hippomu-media** [Mateus7G/crp-iframe-player#19]
Iam using kiwi browser in android, how to change hard subtitle english to non subtitle video?

**Comment by Mateus7G** [comment]
haven't really thought about it yet tho
you might change the hard subs to other lang but crunchyroll doesn't have a 'non-subtitle' option... expect me to develop it soon


anyways, you can't do it on kiwi browser for now... if you **need** it asap, download chrome version, add two breakpoints:
when 1st hits, change `user_lang = null` 
when 2nd hits: change it back to `user_lang = ["enUS"]`

![image](https://user-images.githubusercontent.com/13335925/125652995-5ab2e6f5-f9d5-4639-801f-23cbd6df7e1e.png)

**Comment by hippomu-media** [comment]
Thanks,

--------------
This link: https://fy.v.vrv.co/evs/ad5f0070b3d1cd40d97fac07f47e19c0/assets/ff40b060c7dfe6d7cf0f71d3438032a7_3692368.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9hZDVmMDA3MGIzZDFjZDQwZDk3ZmFjMDdmNDdlMTljMC9hc3NldHMvZmY0MGIwNjBjN2RmZTZkN2NmMGY3MWQzNDM4MDMyYTdfLDM2OTI0MDgubXA0LDM2OTI0MTUubXA0LDM2OTI0MDEubXA0LDM2OTIzODcubXA0LDM2OTIzOTQubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjYyMjgxMjR9fX1dfQ__&Signature=VW-T3oMpCvdNfCT9rDlHlCnAo1frrM0-B31MKcs1IVoMJXbPCE-XkHsaZX0P9smd6bFsvawXDRpj1V1WuL44YWWy2~Sp70zx4u9yPeckwuwktfHztwWj7ZDyXO7K~aJJbZDoHHTSZSn5fGLnOgL44u6q7-muvHXCV5dX9vZsd6k8oC9~d4K7G1od4h5Kxn8eOw5rjmv6hBRGSmKQlCPQrzWx7iB0HK74XpDgIJLjpX9LLc3EEb07C04fM3g0jF9duW6Ti75NczooW2Ex5FVw32VfSsfHqeYtxV7UHbri1YHaZ2OMCZHR26BxvGu~e1AguWO9oOkwG4Ysl6MU9A8a5g__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA

how long does the download link expire and can't be used anymore?

**Comment by erickyun** [comment]
> haven't really thought about it yet tho you might change the hard subs to other lang but crunchyroll doesn't have a 'non-subtitle' option... expect me to develop it soon
> 
> anyways, you can't do it on kiwi browser for now... if you **need** it asap, download chrome version, add two breakpoints: when 1st hits, change `user_lang = null` when 2nd hits: change it back to `user_lang = ["enUS"]`
> 
> ![image](https://user-images.githubusercontent.com/13335925/125652995-5ab2e6f5-f9d5-4639-801f-23cbd6df7e1e.png)

Can also be done with Edge browser? 
Also İf it is possible then how?

**Comment by Mateus7G** [comment]
i said to use chrome breakpoints cause i think it's easier w/o having to changing source, but you might edit the extension code just like i pointed:
arrow 1) add user_lang = null (allowing to find the urls with no subtitles)
arrow 2) add user_lang = "enUS"

**Comment by erickyun** [comment]
I understand thank you for your answer  
actually I'm noob and found how to do this just now 😅

does the player not support subtitles btw?

**Comment by Mateus7G** [comment]
yes jwplayer support subtitles but for that you'd have to scrap where are the subtitles (may be easy for free episodes but not sure about premium ones, meanwhile hardsubs are already there to use), there's even an issue in this repo for this btw

**Comment by erickyun** [comment]
> yes jwplayer support subtitles but for that you'd have to scrap where are the subtitles (may be easy for free episodes but not sure about premium ones, meanwhile hardsubs are already there to use), there's even an issue in this repo for this btw

Could you maybe show/tell me how to do it?

**Comment by erickyun** [comment]
> anyways, you can't do it on kiwi browser for now... 

@hippomu-media 
This can also be done with Kiwi browser now with developer tools.

Just Wanted to notify everyone this intel. 🙂
