### ISSUE TITLE
Extensão trava no loading

### ISSUE THREAD

**Issue by m4sterin** [Mateus7G/crp-iframe-player#2]
A extensão fica em um loop nesse load conforme a imagem, na extensão que eu utilizo esta apontada pra esse git, só reportando mesmo o problema...
![image](https://user-images.githubusercontent.com/42187123/112536313-1019db80-8d8c-11eb-956e-36643dc0dae4.png)

**Comment by Mateus7G** [comment]
tlgd, a crunchyroll mudo os link q ficava os video anteontem e quebro a extensao...
to tentano arruma mas nn garanto mta coisa

**Comment by MontoyaAndres** [comment]
Hi @Mateus7G I don't speak Portuguese, but I've been using this extension and I really like it, would be great if you give more technical details about the problem, I'd like to help you if is possible :).

**Comment by m4sterin** [comment]
@MontoyaAndres Mateus said Crunchyroll changed the link where the videos are found, and this braked the extension, hes trying the solve the problem

**Comment by Enrico712** [comment]
@Mateus7G Força ai mano, eu não sei mexer com programação, mas se puder ajudar de outra maneira ficaria feliz. Essa extensão é boa demais. Se tu conseguir, manda teu insta ou rede social, pq ai eu falo pra te seguirem no vídeo que eu fiz ensinando a usar a extensão como agradecimento :)

O link do meu vídeo ae: https://youtu.be/aB01Ss4feZk

**Comment by Mateus7G** [comment]
Acabei de testar tudo por aqui, pra quem quer entender oq aconteceu ou quer ajudar, a crunchyroll usa um sistema de assinatura da [aws](https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html) pra evitar acesso publico dos videos e streams, essa extensão usava o `dl.v.vrv.co` pra baixar os videos diretos e burlar essa assinatura, acontece q a crunchyroll desativou esse subdominio e agora pros videos premium só da pra pegar os 2 primeiros minutos. Claro, ainda da pra acessar para os videos gratuitos por um .m3u8 assinado em outro lugar (item 1.), mas muito improvavel que essa extensão volte a funcionar.  

Aqui estão alguns domínios e endpoints (nenhum consegue mais acessar conteúdo premium):
```
1: https://www.crunchyroll.com/xml/?req=RpcApiVideoPlayer_GetStandardConfig&media_id=<MEDIA_ID>&video_format=0&video_encode_quality=0&auto_play=1&show_pop_out_controls=1&current_page=http://www.crunchyroll.com/
2: https://pl.crunchyroll.com/
3: https://a-vrv.akamaized.net/
4: https://v.vrv.co/
5: https://dl.v.vrv.co/
```

<details><summary>Legenda</summary>

1. Api em xmlrpc para obter o .m3u8 dos videos e legenda (.ass) codificada, <code>&lt;MEDIA_ID&gt;</code> é o numero q fica no final da url do episódio. Aqui vc consegue o link pra .m3u8 direto já com assinatura na tag <code>&lt;file&gt;</code>, mas não funciona pra videos premium.
2. Subdominio principal q liga todos os manifestos, nao da pra pegar o video premium aq pois precisa de uma assinatura.
3. Uma CDN q ficam os videos da cr, a assinatura dessa é diferente pq usa uma especifica da [akamai](https://learn.akamai.com/en-us/webhelp/cloud-wrapper/cloud-wrapper-user-guide/GUID-0E2A2EAD-8605-40F3-814B-A3B3B17C5D61.html), vc consegue uns exemplos do .m3u8 do primeiro link, so q como o primeiro link nn funciona com premium nn da p faze mta coisa.
4. Outra CDN, aq eh onde fica o acesso direto aos segmentos dos videos mas usa a assinatura da aws.
5. Por aqui era possível baixar os videos direto, agora não da mais.
</details>

**Comment by Mateus7G** [comment]
enquanto não achamos nenhum ponto de acesso livre quem ta aq só pra ver anime hd tem bastante em animeshouse.net

**Comment by Andrey0800770** [comment]
Vocês já tentarão o domínio:https://fy.v.vrv.co

**Comment by Mateus7G** [comment]
Sensacional @Andrey0800770! vou atualizar a extensão

**Comment by Andrey0800770** [comment]
Oloko Nice!

**Comment by Mateus7G** [comment]
Tudo certo 🕵️  
Outro dia eu arrumo o botão de download
Pra quem nn atualizou ainda espera umas horinhas ou abre em guia anonima :+1:

**Comment by carlos7g219** [comment]
![Screenshot_20210327-201622_Kiwi Browser.jpg](https://user-images.githubusercontent.com/81324987/112740351-8b6cc000-8f39-11eb-8d15-94809a9595b9.jpg)

Muito obrigado, nós te agradecemos por este ótimo trabalho, nós te amamos✌

**Comment by Enrico712** [comment]
AEEEEE, boa galera! Valeu pela ajuda @Andrey0800770, salvou nóis kkkkkkkkk, obrigado de verdade. Valeu @Mateus7G, sabia que você ia conseguir, meus parabéns. Deixa ai uma rede social sua pro pessoal te seguir, é o mínimo que nós podemos fazer para te agradecer :))

**Comment by Mateus7G** [comment]
rlx @Enrico712 skdajskdj valeu precisa nao
vlw dnv @Andrey0800770 fez a boa
:)

**Comment by Enrico712** [comment]
@Mateus7G Haha tranquilo então mano, você quem sabe, mas mesmo assim tem minha gratidão e de uma pá de gente. Ah, e é claro, grato também pelo anjo da vez, vulgo @Andrey0800770. Tamo junto rapaziada :D

**Comment by carlos7g219** [comment]
![Screenshot_20210328-213351_Kiwi Browser.jpg](https://user-images.githubusercontent.com/81324987/112783850-80835f80-900d-11eb-9401-57f48293634a.jpg)

Uma pergunta corrige o botão de download?

**Comment by Mateus7G** [comment]
vou sim @carlos7g219, mas talvez não hoje :s

**Comment by Mateus7G** [comment]
@carlos7g219 botão de download arrumado (caso não tenha atualizado espere um pouco ou entre em guia anonima).
vou fechar essa issue, se alguem tiver algum outro problema cria outra
