### ISSUE TITLE
Baixe vídeos de animação

### ISSUE THREAD

**Issue by Carlos502gt** [Mateus7G/crp-iframe-player#21]
Olá, tenho uma pergunta, existe uma maneira de baixar vídeos do funimation?

**Comment by Mateus7G** [comment]
nao testei ainda mas tem um software sim. nem sei se funciona com videos premium, se quiser baixar e testar: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta
