### ISSUE TITLE
Erro ao executar video

### ISSUE THREAD

**Issue by axmxs** [Mateus7G/crp-iframe-player#23]
esta aparecendo a seguinte mensagem de erro...

Este arquivo de vídeo não pode ser reproduzido.
(Código de Erro: 224003)

eu uso no google Chrome PC

mais alguém com esse problema?

**Comment by Mateus7G** [comment]
se for no filme de kimetsu, da uma olhada aqui: https://github.com/Mateus7G/crp-iframe-player/issues/22

**Comment by axmxs** [comment]
Então... na verdade é em todos os animes que ainda estão privado, que estão disponíveis apenas pra quem é premium., sempre aparece o erro citado acima....

fiz o texte no navegador kiwi pelo celular e funcionou, parece que o problema é sono google Chrome Computador (PC)

**Comment by Mateus7G** [comment]
aparentemente pra todo mundo ainda ta funcionando normal no chrome tb... tenta o seguinte:
1) vai no final da página e confirma se o idioma ta em Português (Brasil): 
![image](https://user-images.githubusercontent.com/13335925/142057168-ca0d8422-6f04-43d5-867e-5f533212ca83.png)
2) se der `F5` e ainda não tiver funcionando, desativa o adblock e aperta `Ctrl + Shift + I`, vai em `Console` e manda um print da tela

**Comment by axmxs** [comment]
![Captura de Tela (601)](https://user-images.githubusercontent.com/17688998/142059478-afeda12a-1358-46f6-b832-bbb62b3adc30.png)

**Comment by Mateus7G** [comment]
acabei de testar aqui no chrome 96.0.4664.45/64bit e nao consigo replicar esse erro (`net::ERR_CONTENT_DECODING_FAILED`), e não há muito oq eu possa fazer já que eu nao posso mudar os cabeçalhos q vem da vrv.co, mas vc pode tentar essas opções:
- atualizar o chrome (se for possível)
- tentar desativar as extensões q vc tem no chrome e ver se por acaso alguma delas está causando esse conflito
- instalar a extenção ModHeader, entrar nesse site ai q apareceu no erro (fy.v.vrv.co/evs/.....) seguindo os passos da solução 1 desse site: https://appuals.com/how-to-fix-err_content_decoding_failed-error/ (se quiser pode testar as outras soluções também)
- se nada funcionar, tenta usar a extensão com o opera ou opera gx

**Comment by axmxs** [comment]
->chrome atualizado como mostra a imagem.
->Desativei todas as extensoes e o problema continua
->fiz a instalação do plugin mencionado ao entrar no site  (fy.v.vrv.co/evs/.....) ele faz o download do arquivo MP4 do video

porem no crunchyroll o erro citado na primeira mensagem noa aparece, o vídeo é carregado toca alguns segundos depois para e mostra nova mensagem de erro(como mostro na foto)

->testei no Opera e da o mesmo erro da primeira mensagem que enviei, entao o problema noa é no google chrome, talvez seja algo no meu computador, ja que é so comigo que aparece esses  erros

![Captura de Tela (602)](https://user-images.githubusercontent.com/17688998/142186709-7c6479a3-a599-4a65-8fc5-2340e02ff62a.png)
![Captura de Tela (604)](https://user-images.githubusercontent.com/17688998/142186715-8ae2d17f-e2da-47c4-8854-5818cc7fed1e.png)
![Captura de Tela (607)](https://user-images.githubusercontent.com/17688998/142186719-86c89152-ec0e-4c52-a02d-e3ee80bc91bf.png)
![Captura de Tela (608)](https://user-images.githubusercontent.com/17688998/142186723-2284291b-a199-49f8-90ba-7c6da000020b.png)

**Comment by Mateus7G** [comment]
desculpa a demora, bom, como vc mencionou nesse ultimo print o erro (221000) foi diferente do que apareceu no primeiro (224403), é possível que seja alguma configuração da sua rede com seu pc, talvez o firewall ou algo do tipo com seu driver/dns... mas no último print não apareceu nada relevante no console, esses erros em vermelho aparecem pra todo mundo mesmo (ainda que o player funcione) (talvez esteja mais acima nesse 403 forbidden). 
mesmo assim, se nao aparecer nada sobre esse problema de agora, vc pode tentar encontrar alguma coisa relevante na aba network encontrando na response da requisição q o player faz no url do video:

![image](https://user-images.githubusercontent.com/13335925/142464351-27171cf8-145e-4dce-969d-8c4758fc157a.png)

**Comment by joaomiguelqueiroz177-star** [comment]
Bora jogar Minecraft juntos
