### ISSUE TITLE
Crunchyroll Beta

### ISSUE THREAD

**Issue by Guga342** [Mateus7G/crp-iframe-player#24]
Agora com essa nova versão os animes simulcast (e os que tem as coroas) não estão mais funcionando, e agora?

**Comment by Mateus7G** [comment]
houve alguma atualização que quebrou a extensão? parece que os eps premium ainda estão de boa eu acho:

![image](https://user-images.githubusercontent.com/13335925/144671252-e6aab00d-bf8c-497a-bc9e-06468edc74f2.png)

é possível que seja um problema que ainda nao consegui reproduzir (igual na issue #23)

**Comment by Andrey0800770** [comment]
A extensão ainda funciona, porém quando essa atualização deixar de ser beta a extensão deixará de funcionar

**Comment by Guga342** [comment]
Não irmão não é isso, é que meu Crunchyroll tava com esse design e eu não sabia se a extensão ainda estava funcionando nessa versão nova do site da Crunchyroll, fucei aqui e consegui voltar pro design antigo e está funcionando de boas os simulcasts, mas nesse "Crunchyroll Beta" não funciona os simulcasts (mas os animes funcionam de boa sem anúncios).
![Crunchy beta](https://user-images.githubusercontent.com/70424040/144685251-e3316f6d-f9fc-49f2-8d3a-0e0124faa969.png)

**Comment by Mateus7G** [comment]
ahhh sim, ativei o beta aqui...
parece que ta ficano igual a funimation, sem um playback c/ o trailer de um episódio nos videos premium :(

se eles trocarem a versão atual por essa beta definitiva acho que dificilmente o player voltará a funcionar:
agora eles não estão enviando os dados do video direto na página, e sim consumindo uma API deles, e infelizmente ela não vem com a url do playback nos videos premium (muito menos com um trailer pra poder abusar do bug do fy.v.vrv.co)...

1) Usando a API em um **ep normal**:
![image](https://user-images.githubusercontent.com/13335925/144695164-bd138395-8ffa-4785-aaa2-a3f38191c236.png)

```
CR antigo: https://www.crunchyroll.com/pt-br/the-worlds-finest-assassin-gets-reincarnated-in-another-world-as-an-aristocrat/episode-8-rites-of-choice-819701
CR novo: https://beta.crunchyroll.com/pt-br/watch/GD9UV2MPV/rites-of-choice
CR novo (api): https://beta-api.crunchyroll.com/cms/v2/BR/M3/-/objects/GD9UV2MPV?locale=pt-BR&Signature=EPd0zPYj6qY7VGVq9ukp~-oQ7G02ST9xCIki1~vQ6TiMu3YkSPq2z7JusXODDOgCWUBEW5GTo0ftAgZ5Zm43oI56MOt2arDVgQiEGH6G3Z~tKN~iMe-R-2HGX4jLlAHZjhZvF3Ig5iLndXhIZaSCiViuI9N6SvH9-ezwuOsqFFqS9Hw7Ba5Z4oftJmhq2wtpbX9p6OmtwzZlyzaa~9OnCoXcON8USM8U0V-8khVPsJ5O7BfThbXaZaRNlUlMml2YlNcckgBWees7Ife~JB-z5mJsPWzL7RPD4efg8vAZqgJCl2AwuOw5dkVhnomSDfgo4rD2i0eTcLvxvZ4EqnOogQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L0JSL00zLy0vKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzODY3MjQ0Mn19fV19&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
```

2) Usando a API em um **ep premium**:
![image](https://user-images.githubusercontent.com/13335925/144695170-89492bbd-c5d2-409a-b56e-5fb7a15154c3.png)

```
CR antigo: https://www.crunchyroll.com/pt-br/the-worlds-finest-assassin-gets-reincarnated-in-another-world-as-an-aristocrat/episode-9-compensation-of-assassination-819702
CR novo: https://beta.crunchyroll.com/pt-br/watch/GQJUGE5PM/compensation-of-assassination
CR novo (api): https://beta-api.crunchyroll.com/cms/v2/BR/M3/-/objects/GQJUGE5PM?locale=pt-BR&Signature=epFYUOz5PLvvH~F2AUpfV09-Ce~aHjWZvGsF2MsddcjAyMzQ30WE~ubL4ldsbrikxpOOYmjtPmJZAHAuckgO1pCWtFJdgkfZ6ovTmWNaLlnDUD8Ei6erokzjixQHyA05yMZi0DGjmjBpbc55mOw0qC8hH1SDoMcM5JxZKrxvE1V6c-XOvCaWPoWyOYL3mUjCaEoT5Bp6-9RqdF-S5pOgp2J00FL9rAnoUQYSav9jnZi8EvaFqXSFn6h8PM2iyh~Uc3hR6Kjgx20jfYm7BvNvRBCWqBpou1o-OPGExEL2rFYlukxeCd98MLEFlCCmbpQypExT275BrFPprF-LtQXVZw__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L0JSL00zLy0vKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzODY3MzcwN319fV19&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
```

Vou continuar investigando porém por enquanto sem sinal dos vídeos (premium) no novo beta

**Nota**: hoje (04/12) não existe um link de playback ou trailer no 2° link, quando o ep ficar gratuito para quem for ver essa issue no futuro, a url aparecerá normalmente

**Comment by jikasu1121** [comment]
tem algum jeito de assistir no beta ?

**Comment by flixmu** [comment]
please add beta premium

**Comment by Axe090** [comment]
> please add beta premium

Not possible according to the dev as the trial loophole has been patched in the beta.

**Comment by Mateus7G** [comment]
adicionei compatibilidade com o CR Beta, porém ele é >**completamente dependente**< do CR Antigo.
se por acaso o beta substituir o site antigo, a extensão vai permanentemente parar de funcionar =/

devido a problemas com cors ainda não atualizei a extensão do Kiwi.

**Comment by jikasu1121** [comment]
![image](https://user-images.githubusercontent.com/97318337/151609997-ade1e409-7384-4aeb-9953-78a40122d89e.png)

**Comment by jikasu1121** [comment]
como que eu faço para assistir ?
