### ISSUE TITLE
Erro de reprodução (TIM Live)

### ISSUE THREAD

**Issue by Xinnyyu** [Mateus7G/crp-iframe-player#25]
![image](https://user-images.githubusercontent.com/95600876/144783248-37ad79a8-0702-46e9-b517-47280c948f66.png)

isso ta dando pra mim em todos os animes.

tem como concertar?

**Comment by Mateus7G** [comment]
desativa o adblock e aperta `Ctrl + Shift + I`, vai em `Console` e manda um print da tela
muito provavelmente se aparecer `net::ERR_CONTENT_DECODING_FAILED` deve ser o mesmo problema da #23, mas por enquanto não houve casos de pessoas conseguindo reproduzir esse erro...

**Comment by Xinnyyu** [comment]
![image](https://user-images.githubusercontent.com/95600876/144911357-a1287acd-a3d0-4027-a35f-61c8918a4ef1.png)

isso?

**Comment by Mateus7G** [comment]
hmmm seu problema aparentemente é outro, poderia mandar aquele link completo?

![image](https://user-images.githubusercontent.com/13335925/144917844-2701e0ae-a21c-4f3f-aeb2-e089febd30dc.png)

**Comment by caiquectt** [comment]
eu estava tendo o mesmo probema, e estranhei que mesmo sem a extensão, meus videos não estavam carregando. fui procurar pelo fórum da crunchyroll por uma solução e achei isso:

https://www.crunchyroll.com/forumtopic-1069921/tem-internet-tim-live-e-seus-vdeos-no-carregam-veja-o-tutorial-para-resolver-o-problema

aparentemente quem tem internet da TIM Live ta tendo problemas para carregar os videos da crunchyroll, então se você mudar o DNS os videos voltam ao normal e a extensão volta a funcionar (não sei se é o mesmo problema pra todo mundo, mas funcionou aqui)

**Comment by Xinnyyu** [comment]
DNS?

**Comment by Xinnyyu** [comment]
ata, acabei de fazer aq e foi. muito obg :3

**Comment by Xinnyyu** [comment]
@Mateus7G @caiquectt vlw pela atenção <3
