### ISSUE TITLE
Funimation 

### ISSUE THREAD

**Issue by AngeloGS23** [Mateus7G/crp-iframe-player#26]
Gostaria de perguntar a você @ Mateus7G se você poderia fazer uma extensão como o chunchyroll mas com a página Funimation que seria outra página para assistir anime, eu agradeceria muito.

**Comment by Mateus7G** [comment]
ja respondi essa pergunta num commit: https://github.com/Mateus7G/crp-iframe-player/commit/c201dc2e2639ea5e99e1dc663188809057ea9d8e#commitcomment-49381531
essa extensão explora um bug de validação das policies nos trailers da crunchyroll no dominio da vrv, o mesmo nn é possível com a funimation já que o site deles não tem trailers nos animes premium :(

um ponto interessante a levantar aqui é que a nova versão do cr (crunchyroll beta) tb não tem trailers p/ eps premium, ou seja, não vai ter mais como assistir caso eles substituam completamente a plataforma (sem poder optar pela versão antiga).
caso seja permitido escolher entre as versões to vendo a viabilidade de assistir os eps no layout novo puxando os trailers pelo layout antigo por uma [proxy](https://github.com/Mateus7G/allOrigins) -> ex: http://crp-proxy.herokuapp.com/vilos?url=https%3A%2F%2Fwww.crunchyroll.com%2Fpt-br%2Fattack-on-titan%2Fepisode-809513
no caso não da pra fazer o msm com a funimation já que eles não disponibilizam trailers em lugar algum...

**Comment by KINGASN002** [comment]
nao sei se vc vai ler isso mais agora so ta ficando Seu video iniciara em instantes (^-^)
Aguardando dados da stream.. e nao sai disso

**Comment by diegopaul2014** [comment]
Muchas gracias por la extensión,  tengo unas preguntas la extensión dejará de funcionar en el 2023? , tienes más extensiones así o solo hay esta nomas disponible?

**Comment by julivanio** [comment]
@Mateus7G ajuda nois doido kk

**Comment by ANDRES25X** [comment]
Ele se foi para sempre :'c

**Comment by DARLINGzt** [comment]
Atualizar a extensão pls

**Comment by waltervi666** [comment]
ai namoral chego uns anime bom dai o baguio para de funfa kkkkkkk salva nois

**Comment by mrpandix** [comment]
https://user-images.githubusercontent.com/97079235/197437988-12146fa0-379f-4226-a6b5-af2ecc5223c5.mp4
doesn't work anymore :c

**Comment by Matheus-Luan** [comment]
Talvez por isso q parou 
https://github.com/Mateus7G/crp-iframe-player/issues/109

**Comment by fekete1** [comment]
RIP

**Comment by SamLeal01** [comment]
@Mateus7G Mateus ajuda nós, a extensão da Crunchyroll versão 1.2.1 não funciona mais. Fica aparecendo esses 2 erros: Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
Uncaught TypeError: Cannot read properties of undefined (reading 'G4VUQ955W')

Dá essa força ae Mateus

**Comment by di0nar4p** [comment]
R.I.P iFrame Player :'(

Press F to pay respect
