### ISSUE TITLE
Botão para avançar 90 segundos

### ISSUE THREAD

**Issue by julianoaureliano** [Mateus7G/crp-iframe-player#27]
Desde já muito obrigado por criar essa extensão maravilhosa, queria saber se tem como você colocar um botão no player para avançar 90 segundos (o tempo de uma abertura), só para facilitação de uso (ajudaria bastante por incrível que pareça).

**Comment by Mateus7G** [comment]
90s acho que é muito dependendo da op, adicionei um de 30s, 3 cliques resolve
