### ISSUE TITLE
Este arquivo de vídeo não pode ser reproduzido. (Código de Erro: 224003)

### ISSUE THREAD

**Issue by Darkryng** [Mateus7G/crp-iframe-player#28]
Nenhum vídeo premium carrega, já to sem adblock, troquei DNS
Seguindo alguns passos da #23 e #25 

Vou adicionar uns prints do console
![image](https://user-images.githubusercontent.com/98337505/150819898-d468b142-bfed-42cf-a6d8-cf032f4842f1.png)
![image](https://user-images.githubusercontent.com/98337505/150819974-b12a3c78-807f-4464-bb45-0e90eae6a4e2.png)

**Comment by Darkryng** [comment]
Já conferi se a page ta em PT tbm
![image](https://user-images.githubusercontent.com/98337505/150820380-e14e5b6c-81c2-406f-9541-ff55b932cef3.png)

**Comment by Mateus7G** [comment]
seu erro (`net::ERR_CERT_DATE_INVALID`) é diferente das outras issues,
tenta dar uma olhada nesse passo a passo, se nenhum der certo, tenta trocar
o seu navegador pelo opera e instalar a extensão lá pra ver se funciona
normal

**Comment by Mateus7G** [comment]
o github não mandou o link dos possiveis fix por email :/
segue aqui: https://kinsta.com/pt/base-de-conhecimento/net-err_cert_date_invalid/#como-corrigir-o-erro-neterr_cert_date_invalid

vou fechar essa issue por inatividade, se ainda tiver com problemas posso abrir novamente
