### ISSUE TITLE
Nova ferramenta de bloqueio "Evidon: DG"

### ISSUE THREAD

**Issue by guto00741** [Mateus7G/crp-iframe-player#29]
Boa Tarde pessoal,
Hj foi utilizar o plugin  e deu nisso.

![image](https://user-images.githubusercontent.com/7913550/151218848-e8515ab0-bfcd-43b9-8eb8-59d16b4fb794.png)

creio que estão tentando evitar script de usuário com "evidon.com"
por hora consegui evitar essa ferramenta  com o adblock uBlock adicionando a seguinte regra:

! 2022-01-26 https://www.crunchyroll.com
||dgcollector.evidon.com/api/*
||c.evidon.com^$domain=crunchyroll.com

**Comment by Mateus7G** [comment]
imagino que esse problema não está ocorrendo com todos mas vou fixar caso alguem precise, obrigado por informar :+1:

**Comment by Mateus7G** [comment]
update: a nova versão v1.2.1 [bloqueia o evidon por padrão](https://github.com/Mateus7G/crp-iframe-player/commit/c39fdffbbaa04b667b90189311d983f256963b55) :)
