### ISSUE TITLE
Download bugado no celular

### ISSUE THREAD

**Issue by MFMelloReal** [Mateus7G/crp-iframe-player#3]
Toda vez que eu tento baixar algum episódio no meu celular, aparece essa aba e não sai disso, fica carregando pra sempre as opções de download.

Agradeceria muito se vocês consertassem.
![Screenshots_2021-03-29-21-40-05](https://user-images.githubusercontent.com/81598934/112917057-46cb5b00-90d8-11eb-8833-6c4c45ad0f1d.png)
.

**Comment by Mateus7G** [comment]
corrigido, espera alguns minutos e verifica se o erro persiste

**Comment by MFMelloReal** [comment]
> corrigido, espera alguns minutos e verifica se o erro persiste

Os downloads para 720p estão funcionando mas os downloas para 1080p estão bugados, eu clico neles e ele não baixa nada.

**Comment by MFMelloReal** [comment]
> > corrigido, espera alguns minutos e verifica se o erro persiste
> 
> Os downloads para 720p estão funcionando mas os downloads para 1080p estão bugados, eu clico neles e ele não baixa nada.

OBS: Somente na versão de celular, no computador ele baixa tudo direitinho.

**Comment by Mateus7G** [comment]
estranho nao funcionar só no celular sendo o mesmo site nos dois :thinking: 
vc pode verificar se ainda não ta funcionano ou se foi apenas momentaneo?
e se nao foi, tava mostrando 3 pontinhos laranjas ou tava o tamanho do arquivo?
nao vou conseguir testar no celular p verificar :/

**Comment by MFMelloReal** [comment]
> estranho nao funcionar só no celular sendo o mesmo site nos dois 🤔
> vc pode verificar se ainda não ta funcionano ou se foi apenas momentaneo?
> e se nao foi, tava mostrando 3 pontinhos laranjas ou tava o tamanho do arquivo?
> nao vou conseguir testar no celular p verificar :/

Está acontecendo isso aqui: 

https://user-images.githubusercontent.com/81598934/113090224-aea8a100-91bf-11eb-8140-05ae068ce094.mp4

**Comment by carlos7g219** [comment]
Por que os downloads não funcionam em mais qualidades e apenas em 720p?

**Comment by Mateus7G** [comment]
@carlos7g219 este problema só está ocorrendo na versão mobile. estou tentando descobrir desde manhã, porém não tenho um android comigo então talvez demore um pouco

**Comment by carlos7g219** [comment]
Ok, espero que você possa descobrir o erro

**Comment by Andrey0800770** [comment]
Aqui está funcionando perfeitamente,acho que o problema é no navegador, pois eu estou usando uma versão do Chrome modificado para extenções funcionarem

**Comment by Andrey0800770** [comment]
![Uploading Screenshot_20210331-185137.png…]()

**Comment by Andrey0800770** [comment]
![Screenshot_20210331-185137](https://user-images.githubusercontent.com/66447173/113216674-0fcd8480-9253-11eb-9c7f-8f15a63b92ba.png)

**Comment by Andrey0800770** [comment]
Em qual episódio/anime está acontecendo o erro pra mim verificar se é o navegador

**Comment by Andrey0800770** [comment]
Eu instalei o kiwi browser aqui e realmente o problema tá nele,no meu navegador tá funcionando perfeitamente
Pra quem quiser :

Baixe aqui diacordo com seu celular: https://github.com/ungoogled-software/ungoogled-chromium-android/releases/tag/88.0.4324.182-2-extensions

Pra ativar as extensões, na barra de pesquisa digite: `chrome://flags`

Após carregar procure por `Handling of extension MIME type requests
#extension-mime-request-handling`

E marque a alternativa `Always prompt for install`

Após isso digite na barra de pesquisa por: `chrome://extensions/`

Depois marque a opção: `Modo de Desenvolvedor `

Após isso clique em `carregar sem compactação` e carregue o diretorio da  extensão descompactada

**Comment by carlos7g219** [comment]
a extensão está comprimida?

**Comment by Andrey0800770** [comment]
Só se você quiser, pois funciona de ambos os jeitos

**Comment by MFMelloReal** [comment]
> Só se você quiser, pois funciona do mesmo jeito

Cara, não estou conseguindo não. Eu clico sem parar na extensão e não vai e quando eu clico em ''permitir acesso a transferências'' ele dá erro.
![Screenshot (31 de mar de 2021 22_53_32)](https://user-images.githubusercontent.com/81598934/113232721-16202880-9274-11eb-97e5-74db3ef50f17.png)
![Screenshot (31 de mar de 2021 22_52_00)](https://user-images.githubusercontent.com/81598934/113232730-17e9ec00-9274-11eb-8946-522dbe57fa6a.png)

**Comment by Andrey0800770** [comment]
Você terá que permitir acesso a transferências dentro da pasta da extensão extraída mesmo, realmente não dá para carregar a extensão compactada

![Screenshot_20210401-091944](https://user-images.githubusercontent.com/66447173/113293007-9d4cbb00-92cb-11eb-9c2b-221cf8637022.png)

**Comment by Mateus7G** [comment]
acabei de atualizar, nao faço a menor ideia do q eu fiz de diferente mas funcionou no meu emulador :+1:  
já da pra baixar 1080p porem por algum motivo no kiwi ainda nao carrega os tamanhos, vai ficar por isso mesmo

![downloads](https://user-images.githubusercontent.com/13335925/113296011-4d6ff300-92cf-11eb-9ac9-c2d6a8b1439f.png)
