### ISSUE TITLE
problema cr beta

### ISSUE THREAD

**Issue by jikasu1121** [Mateus7G/crp-iframe-player#30]
![image](https://user-images.githubusercontent.com/97318337/151610994-ffe0cfbe-90d7-4bb1-9773-b3869bb1d93a.png)

**Comment by jikasu1121** [comment]
como faço para assistir ?

**Comment by Mateus7G** [comment]
acesse `chrome://extensions` e garanta que a versão está atualizada:
![image](https://user-images.githubusercontent.com/13335925/151662483-3f5b6df2-f175-453d-9450-45247a22f1f1.png)

se não tiver v1.1.0, primeiro vc precisa atualizar a extensão, baixando a mais recente aqui:
https://github.com/mateus7g/crp-iframe-player/releases/latest
substituindo a versão antiga.

muito provavelmente vc ainda não atualizou, mas se já tiver na v1.1.0 e continuar com problemas, 
aperta um <kbd>F5</kbd> pra atualizar, espera um pouco e tira um print do Console (apertando <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> no site do video da crunchyroll)
