### ISSUE TITLE
Cr beta not compatible on android? Why?

### ISSUE THREAD

**Issue by flixmu** [Mateus7G/crp-iframe-player#31]
Please make it compatible on kiwi

**Comment by Mateus7G** [comment]
as i've mentioned @ https://github.com/Mateus7G/crp-iframe-player/issues/24#issuecomment-1022755102 i'm having cors issues on kiwi.

the v1.1.0 version (working on desktop) is bypassing cors [by appending](https://github.com/Mateus7G/crp-iframe-player/blob/432daadb7ff94f2a1450213981f6ea792e17e39a/Crunchyroll_Premium/background.js) an `Access-Control-Allow-Origin: *` header to all crunchyroll responses. However, when I tried using this listener on Kiwi, i was having a lot of cors errors: basically this approach wasn't working.

I'll try again and deep debug it as soon as I get more time to do so, but for now it isn't compatible and **i'm yet not sure if this background script will work or not** on kiwi tho. I'll write to this issue back in a week.

**Comment by Mateus7G** [comment]
Just updated Kiwi version, you can download it at: https://github.com/Mateus7G/crp-iframe-player/releases/latest
