### ISSUE TITLE
A opção Chromecast não está funcionando para eps free

### ISSUE THREAD

**Issue by Zhengola** [Mateus7G/crp-iframe-player#33]
Eu uso essa opção para poder ver na minha tv, estava funcionando para ver obras q são somente para premium, porém quando fui tentar assistir outros q são liberados não deu certo, na primeira vez, ele aparecia uma parte do ep e dps pulava de episódio e fechava.

**Comment by Mateus7G** [comment]
Na verdade o player não estava configurado p/ funcionar com o chromecast anteriormente.
Fiz uma alteração em 55d664b31cd00404d594371b7e95c9f410eb7e2e mas não consigo testar, poderia confirmar se foi corrigido?

**Comment by Zhengola** [comment]
se estava ou não configurado, como eu faço para pegar essa alteração? O problema de não aparecer sumiu (eu acho q no dia eu acabei desligando a tv), porém o problema com os eps liberados bugar quando ativo a opção ainda persiste.

**Comment by Mateus7G** [comment]
não precisa, as alterações na pasta assets/js são atualizadas automaticamente.

mas sobre os liberados, a unica diferença dos eps frees e premiuns é que:
- free: o player carrega um .m3u8
- premium: o player carrega um .mp4

talvez seja esse o motivo do problema, e eu não queria resolver isso fazendo o free carregar o mp4 também pq acaba deixando o loading mais lento:
- #8

aqui em casa não funciona a opção de chromecast na tv, então eu uso o midiacast pra transmitir a tela do celular msm, talvez seja uma alternativa

**Comment by Zhengola** [comment]
hm entendi, uma boa alternativa

**Comment by Zhengola** [comment]
mas eu nunca tive problema de carregamento nos eps premium, talvez isso dependa da velocidade de internet

**Comment by Zhengola** [comment]
mas por que o chromocast buga quando eu boto ep free? é por causa do .m3u8? Será q da pra corrigir? Ou forçar um .mp4 (pelo visto funciona com esse)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/85583178/156901967-ed359b00-1bef-4af7-9661-fc8321573b1f.gif)

**Comment by Mateus7G** [comment]
é possivel que seja o .m3u8 que ta bugando por algum motivo sim, já que é a unica diferença entre o free e o premium...

MAS tem algo que vc pode tentar. como o jwplayer ta identificando o ep como "terminado" e começando outro logo em seguida, vc pode tentar desativar a opção "a seguir" na própria extensão e ver se esse workaround funciona pra vc:

![image](https://user-images.githubusercontent.com/13335925/156902837-73f9d33d-0341-4bf2-ab79-4ef3f941d55e.png)

**Comment by Zhengola** [comment]
desculpe o incomodo, mas nada mudou...
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/85583178/156903379-0a117d7c-3e9c-452e-ae8f-90c9e1b5f526.gif)
mas em comparação a um ep premium
![ezgif com-gif-maker](https://user-images.githubusercontent.com/85583178/156903384-b3f92af4-0915-4bdb-a895-42919ef66f98.gif)

**Comment by Mateus7G** [comment]
bom se o problema for o .m3u8 mesmo eu subi um update em d1bea382d754925388167611da02eb8d4617af81, essa versão vai forçar o .mp4 nos eps frees tbm.

pra forçar o .mp4 você vai precisar baixar essa extensão alterada: [Crunchyroll_Premium_Casting_Workaround.zip](https://github.com/Mateus7G/crp-iframe-player/releases/download/v1.1.0/Crunchyroll_Premium_Casting_Workaround.zip) da [v1.1.0](https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.1.0).

se funcionar pra você forçando o mp4 assim, posso no próximo update adicionar um toggle igual o "A seguir automático" na extensão pra todo mundo...

**nota:** da extensão em si, só mudei o content.js pra mandar um `playerInfo['force_mp4'] = true;`

**Comment by Zhengola** [comment]
agora fica carregando eternamente, eu testei com a extensão antigo e carregou numa boa (me refiro aos eps free) 😔

**Comment by Mateus7G** [comment]
talvez o codigo da d1bea382d754925388167611da02eb8d4617af81 ainda não atualizou aí, tenta limpar o cache do site: http://mateus7g.github.io/crp-iframe-player e teste novamente a extensão com o fix
se mesmo assim não funcionar você pode conferir no Console se aparece algum erro da extensão na hora de fazer o casting e  mandar aqui

**Comment by Zhengola** [comment]
![2022-03-06](https://user-images.githubusercontent.com/85583178/156924142-33f52140-b654-4eae-9e4a-38ef5a1adb22.png)
![2022-03-06 (1)](https://user-images.githubusercontent.com/85583178/156924146-666e0a86-67d5-4321-adf1-7fb4bd3d1f85.png)
![2022-03-06 (4)](https://user-images.githubusercontent.com/85583178/156924151-9c0b96f1-b04e-4919-95bc-1b237f208521.png)
![2022-03-06 (3)](https://user-images.githubusercontent.com/85583178/156924157-bf3d3d1f-9458-4089-a50a-280ba41ba297.png)

**Comment by Mateus7G** [comment]
infelizmente nenhum desses erros indicam algo errado na extensão... :crying_cat_face: 
sugiro tentar o basico mesmo: desativar adblocks, trocar a qualidade do video, testar o casting em outro navegador pra ver se funciona (chrome/opera) etc..

não consegui reproduzir esse problema aqui e se nada der certo recomendo espelhar ou fazer igual aqui, usando o midiacast c/ o kiwi browser pelo celular

**Comment by Zhengola** [comment]
meh, talvez eu esteja exigindo demais. Testei em outros navegadores e todos apresentaram o mesmo erro, talvez n dê certo forçar reproduzir em .mp4, parece q os servidores bloqueiam, sla

**Comment by Mateus7G** [comment]
@Zhengola fiz algumas alterações na extensão, se possível verificar se os EPs free já estão funcionando no chromecast na nova versão [v1.2.0](https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.2.0), tente definir a seguinte opção na extensão e atualize a página:

![image](https://user-images.githubusercontent.com/13335925/177418259-7b3eef83-d895-4406-87f7-66d87414ef90.png)

**Comment by Mateus7G** [comment]
como mencionado na https://github.com/Mateus7G/crp-iframe-player/issues/46#issuecomment-1177536044, os blobs devem ter sido o problema nos eps free, estou fechando essa issue mas caso ainda haja algum problema favor reabrir
