### ISSUE TITLE
Aguardando dados da stream..

### ISSUE THREAD

**Issue by Mateus7G** [Mateus7G/crp-iframe-player#34]
nao sei se vc vai ler isso mais agora so ta ficando Seu video iniciara em instantes (^-^)
Aguardando dados da stream.. e nao sai disso

_Originally posted by @KINGASN002 in https://github.com/Mateus7G/crp-iframe-player/issues/26#issuecomment-1058788649_

**Comment by Mateus7G** [comment]
@KINGASN002 se possível poderia abrir o Developer Tools (Ctrl + Shift + I) e postar um print do Console?

**Comment by Zhengola** [comment]
esse problema ocorreu recentemente, mas eu percebi que isso predomina nos eps liberados. Quando isso ocorre eu reinicio a página, se não funcionar eu reinstalo a extensão (desculpa a minha intromissão)

**Comment by KINGASN002** [comment]
![image](https://user-images.githubusercontent.com/89954895/156893092-cc861034-8cd1-4f53-aa2e-aed5fe8eb993.png)

**Comment by KINGASN002** [comment]
te juro volto ao normal hj nao sei pq nao tava pegando antes

**Comment by Zhengola** [comment]
o problema é que ele para de funcionar depois de um tempo, ai eu tenho q repetir esse mesmo processo, mas os eps premium isso nunca aconteceu

**Comment by Mateus7G** [comment]
bom se foi temporário tudo bem, mas qualquer coisa essas mensagens que vc printou não são relacionadas ao player.
muito provavelmente o erro é o que ficou cortado ali em cima na foto

**Comment by KINGASN002** [comment]
entendo

**Comment by Maycon40gamer** [comment]
pra mim aqui não esta mais funcionando, só fica carregando e não abre o video

**Comment by Mateus7G** [comment]
@Maycon40gamer qual versão da extensão está usando? (por favor utilize a mais recente: v1.2.0)

**Comment by Maycon40gamer** [comment]
sim essa mesmo

**Comment by Mateus7G** [comment]
a extensão ta de rodando de boa tanto pra eps free quanto pra premium por enquanto... tenta reinstalar pq vc pode ter perdido alguma dessas permissões sem querer:

![image](https://user-images.githubusercontent.com/13335925/178628071-892b3ef5-1033-4eaf-a836-60dd87f25f53.png)

fora isso, se ainda não funcionar por favor mande prints do console (Ctrl+Shift+J) com os erros que estiverem abaixo da ultima mensagem da extensão (`[CR Premium] ...`)

**Comment by Maycon40gamer** [comment]
vou tentar

**Comment by Maycon40gamer** [comment]
obrigar funcionol
![Sem título](https://user-images.githubusercontent.com/109188078/178629305-9cbed130-43ea-4154-85f5-86c9aa0e8722.png)
