### ISSUE TITLE
Futura Adaptação de Manifesto

### ISSUE THREAD

**Issue by Fel1pr** [Mateus7G/crp-iframe-player#36]
Não preciso dizer nada, com o tempo e a entrada do manifesto V3,  teremos problemas
![image](https://user-images.githubusercontent.com/101002836/156956977-6fbbe58d-9a02-4b25-8335-0a5b8360a853.png)

**Comment by yoitscarolinee** [comment]
substitui esse role aqui no manifest.json

`{
	"name": "Crunchyroll iFrame Player",
	"version": "1.1.0",
	"description": "Permite ver todos os vídeos do crunchyroll gratuitamente.",
	"author": "itallolegal",
	"icons": { "48": "icon.png" },
	"action":{
		"default_title": "Crunchyroll iFrame Player",
		"default_popup": "popup.html",
		"default_icon": "icon.png"
	},
	"permissions": [
    "declarativeNetRequest",
    "declarativeNetRequestFeedback",
    "http://localhost/*",
    "https://pl.crunchyroll.com/*",
    "https://www.crunchyroll.com/*",
    "https://*.mateus7g.github.io/*",
		"storage"
  ],
	"content_scripts": [
    {
      "matches": ["https://*.crunchyroll.com/*"],
      "css": ["content.css"],
      "js": ["content.js"],
      "run_at": "document_start"
    }
  ],
  "background": {
    "service_worker": "background.js"
  },
	"manifest_version": 3
}`

**Comment by Mateus7G** [comment]
> Não preciso dizer nada, com o tempo e a entrada do manifesto V3, teremos problemas

boa :+1: vou atualizar assim que possivel

**Comment by Mateus7G** [comment]
Obrigado novamente pela issue, corrigido na [v1.2.0](https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.2.0)!

**Comment by yoitscarolinee** [comment]
@Mateus7G se precisar de qualquer ajuda pra issue eu posso ajudar também!

**Comment by Mateus7G** [comment]
muito obrigado @yoitscarolinee pela ajuda! essa do manifesto já foi resolvida e a unica issue aberta agora é a do chromecast, essa eu não consigo testar pois não tenho um aparelho aqui :pensive: 
mas se quiser fique a vontade para dar watch no repositório e receber notificações caso novas issues sejam criadas:
![image](https://user-images.githubusercontent.com/13335925/178143616-c86a1360-8679-42ce-b39e-b4ec6ce13ebb.png)
