### ISSUE TITLE
Alterar idioma da legenda

### ISSUE THREAD

**Issue by kuriipa** [Mateus7G/crp-iframe-player#37]
Existe uma maneira de alterar o idioma da legenda?

**Comment by kuriipa** [comment]
> Existe uma maneira de alterar o idioma da legenda?

**Comment by Mateus7G** [comment]
perdão pela demora, mas p/ quem tiver chegando e tbm não souber, é só alterar a legenda do site pelo menu lateral:

![image](https://user-images.githubusercontent.com/13335925/163371852-fa715f4f-4aff-46b7-b979-98f208203799.png)

ou pelo rodapé:

![image](https://user-images.githubusercontent.com/13335925/163371880-70a36b79-3829-4b39-9800-920716759c14.png)
