### ISSUE TITLE
poderia fazer para firefox

### ISSUE THREAD

**Issue by lucateli** [Mateus7G/crp-iframe-player#38]
ou me dar o script pra mim colocar em outro progama pra usar nele

**Comment by Mateus7G** [comment]
> poderia fazer para firefox

não deve ser trabalhoso mas eu não faço por causa da falta de tempo + ter que ficar atualizando mais 1 extensão nesse repo, caso queira fazer vc vai ter que alterar os arquivos de configuração, o CORS do **background.js** e os `chrome.storage` q tao no codigo p salva infos de configuração do usuário (do popup)

se quiser fazer e contribuir com a extensão vc pode abrir uma pull request subindo a versão p/ firefox q eu vou analisar :)

> ou me dar o script pra mim colocar em outro progama pra usar nele

o codigo fonte de toda a extensão esta nesse repo, a do chrome fica em [`/Crunchyroll_Premium`](https://github.com/Mateus7G/crp-iframe-player/tree/master/Crunchyroll_Premium).

**Comment by Rgern100** [comment]
Eu fiz um fork simples [https://github.com/Rgern100/crp-iframe-player-Firefox](url) , não garanto estar funcionando tudo mas em geral tá kkkk
