### ISSUE TITLE
Uma extensão que não mude o design original do site da Crunchyroll

### ISSUE THREAD

**Issue by Vegas07** [Mateus7G/crp-iframe-player#39]
![Screenshot_20220416-141351](https://user-images.githubusercontent.com/103847213/163684909-d76321cb-cb2c-48a2-9167-92663e1ff6e2.jpg)
Oi, boa tarde, queria saber se tem como vc (dono da extensão) fazer uma extensão que n mude o design do site da Crunchyroll. Esta extensão "Crunchyroll_Premium_Casting_Workaround.zip"
N muda o design do site, mas por algum motivo só pega os eps premium, é possível q vc crie uma extensão como esta q pegue os eps free e premium, mas q não mude o design original do site, lembrando q é pra Android, o design da extensão principal pra Android é legal, mas prefiro o design original do site da Crunchyroll , tem como vc dar uma olhada? Se possível. #

**Comment by Vegas07** [comment]
> ![Screenshot_20220416-141351](https://user-images.githubusercontent.com/103847213/163684909-d76321cb-cb2c-48a2-9167-92663e1ff6e2.jpg) Oi, boa tarde, queria saber se tem como vc (dono da extensão) fazer uma extensão que n mude o design do site da Crunchyroll. Esta extensão "Crunchyroll_Premium_Casting_Workaround.zip" N muda o design do site, mas por algum motivo só pega os eps premium, é possível q vc crie uma extensão como esta q pegue os eps free e premium, mas q não mude o design original do site, lembrando q é pra Android, o design da extensão principal pra Android é legal, mas prefiro o design original do site da Crunchyroll , tem como vc dar uma olhada? Se possível. #

**Comment by Mateus7G** [comment]
No Android você deve usar a versão para o Kiwi Browser: [Crunchyroll_Premium_Kiwi-Browser.zip](https://github.com/Mateus7G/crp-iframe-player/releases/download/v1.1.0/Crunchyroll_Premium_Kiwi-Browser.zip).
