### ISSUE TITLE
Preguntas

### ISSUE THREAD

**Issue by diegopaul2014** [Mateus7G/crp-iframe-player#40]
Muchas gracias por la extensión,  tengo unas preguntas la extensión dejará de funcionar en el 2023? , tienes más extensiones así o solo hay esta nomas disponible?

**Comment by Mateus7G** [comment]
> la extensión dejará de funcionar en el 2023?

- a extensão vai parar de funcionar apenas se a crunchyroll remover os trailers dos eps ou se substituir completamente o layout antigo pelo que está em beta https://github.com/Mateus7G/crp-iframe-player/issues/24#issuecomment-1022755102
- porém, se estiver dizendo sobre o aviso do manifesto, isso vai ser corrigido na #36

-----

> tienes más extensiones así o solo hay esta nomas disponible?

só essa mesmo, o criador da extensão desativou a conta e desde que a antiga extensão quebrou estou apenas mantendo atualizado e corrigindo os bugs

**Comment by diegopaul2014** [comment]
A ya, muchas gracias por responderme
