### ISSUE TITLE
Alguns animes em específico não carregam

### ISSUE THREAD

**Issue by Mateus7G** [Mateus7G/crp-iframe-player#41]
Eu criei uma conta gratuita para maior de idade na Crunchyroll pra assistir animes sem censura e usei a extensão, mesmo o episódio não sendo premium o play não carrega. https://www.crunchyroll.com/pt-br/maken-ki/episode-1-the-day-we-swore-to-heaven-737163

_Originally posted by @Pinoia0 in https://github.com/Mateus7G/crp-iframe-player/issues/8#issuecomment-1120274798_

**Comment by Mateus7G** [comment]
@Pinoia0 tinha feito um workaround pra animes do tipo international dub que tbm caiam nesse problema: esses animes com poucas legendas (só pt e ingles) estavam vindo com a `hardsub_lang: null` em vez de `"ptBR"`. corrigi já nesse commit: 
espera um pouco que jajá a correção atualiza pra tu.

**Comment by lucas100000000** [comment]
Would it be possible to make a version of the extension for firefox?

**Comment by Mateus7G** [comment]
> Would it be possible to make a version of the extension for firefox? Teria a possibilidade de fazer uma versão da extensão para o firefox?
@lucas100000000 

Já respondido em: https://github.com/Mateus7G/crp-iframe-player/issues/38
