### ISSUE TITLE
Remover elemento da pagina da Crunchyroll

### ISSUE THREAD

**Issue by NedcloarBR** [Mateus7G/crp-iframe-player#44]
Quando você esta logado (não testei sem logar) e não tem premium aparece um elemento na pagina dizendo para você assinar o premium e esse elemento bloqueia qualquer click na pagina lhe impedindo de assistir o episódio 

# Elemento para ser removido
> `erc-watch-premium-upsell`
![image](https://user-images.githubusercontent.com/55925943/176325719-1880072f-e436-4b78-abcc-0376fd4f583c.png)
![image](https://user-images.githubusercontent.com/55925943/176325752-67dcbb01-0e1a-4be7-8374-ab2d79d0c31d.png)

**Comment by Mateus7G** [comment]
boa! como não uso o layout premium não cheguei a pegar esse, mas vou corrigir junto com o #36 já que pra resolver esse aí tem que alterar os arquivos da extensão e a galera vai ter que baixar novamente

**Comment by PatricioBaeza98** [comment]
@Mateus7G  Olá, em primeiro lugar muito obrigado por tudo que você faz, desculpe o transtorno, mas gostaria de saber se é possível a extensão baixar filmes? Quero baixar um filme mas demora muito para carregar e quando pressiono o ícone de download aparece o seguinte erro "Erro 503 Response object too large" muito obrigado novamente

**Comment by Mateus7G** [comment]
Obrigado novamente pela issue, corrigido na [v1.2.0](https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.2.0)!
