### ISSUE TITLE
Não é possivel utilizar chromecast em episódio antigos

### ISSUE THREAD

**Issue by deprimez** [Mateus7G/crp-iframe-player#46]
Olá, boa tarde, percebi que não é possivel utilizar chromecast em episódios antigos, um exemplo disso é Bungo Stray Dogs episódio 2 (de 2016), não consigo transmiti-lo ao meu dispositivo tv box. E só foi possivel transmitir episódios disponíveis em 2021, abaixo dessa data não tive sucesso. Depois tentei usar a versão "Crunchyroll_Premium_Casting_Workaround" e aí os episódios abaixos de 2021 nem carregavam. Peço porfavor que me ajude a achar uma solução para este problema. 

Obrigado !

**Comment by Mateus7G** [comment]
Olá. A extensão "Casting_Workaround" era um teste para a #33 que infelizmente falhou...
Hoje fiz algumas atualizações para forçar o mp4 sem precisar de uma extensão separada.
Por favor, gostaria de pedir para atualizar a extensão para a [v1.2.0](https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.2.0) e caso ainda não esteja funcionando, tente ativar a seguinte opção na extensão:

![image](https://user-images.githubusercontent.com/13335925/177418064-2cffad60-251b-4e83-adef-93b2b521fd84.png)

**Comment by Mateus7G** [comment]
Poderia testar um F5 limpando o cache segurando Ctrl + Botão de reload da página?
Se tudo der certo console deve ter uma mensagem assim:

![image](https://user-images.githubusercontent.com/13335925/177421910-cdec2472-2f3a-44ea-83f3-80e26875b103.png)

**Comment by deprimez** [comment]
Oi, apareceu a mensagem MAS o player fica carregando infinitamente e antes de aparecer está mensagem, aparece isso aqui : 
![image](https://user-images.githubusercontent.com/108759436/177425099-9903b4a8-2156-4058-b2d2-531680d5b3f0.png)

**Comment by Mateus7G** [comment]
carregando com essa mensagem?
![image](https://user-images.githubusercontent.com/13335925/177448490-729b0aaa-f297-4ce6-9eec-0cc5382fc35c.png)

ou carregando na hora de fazer o cast? se for só na hora de fazer o cast infelizmente já não tenho mais ideia do que fazer :disappointed:

**Comment by Mateus7G** [comment]
@ALISONTS99 este botão é nativo do jwplayer e aparece sozinho (exemplo: https://github.com/Mateus7G/crp-iframe-player/issues/33#issuecomment-1059843318) se houver algum aparelho com a função disponível na mesma rede:

> Casting enables a viewer to use Google Cast or Apple AirPlay technologies to stream video and audio content to a compatible TV or sound system. By enabling the casting feature for a player, a viewer can tap an icon in the control bar to stream your content on a cast-compatible device on the same network. **If no compatible device is detected by the player, no cast icon appears.**

https://support.jwplayer.com/articles/how-to-enable-casting-and-airplay

**Comment by ALISONTS99** [comment]
Obrigado pela resposta, Eu tenho dois dispositivos na minha rede, SmartTV e Xbox One no caso entao ambos nao sao compativeis certo?

**Comment by Mateus7G** [comment]
provavelmente @ALISONTS99. minha tv tbm é smart e permite casting pelo app e no youtube tbm aparece o icone pra fazer o casting direto, mas no jwplayer o icone tbm não aparece...

aparentemente existem diferentes tipos de "cast receivers" e seu dispositivo pode ou não suportar nesse caso...
consegui fazer o ícone de casting do jwplayer aparecer com o app [CastReceiver](https://play.google.com/store/apps/details?id=com.softmedia.receiver.castapp&hl=pt_BR&gl=US) mas ao clicar no botão o player fica em um loading eterno :cry:

**Comment by ALISONTS99** [comment]
@Mateus7G o método que eu uso pra fazer o cast é assim, da certo porém as vezes fica travando, não se tu já sabia desse

Uploading 20220720_183710769.mp4_play.mp4_logo_BR.mp4…

**Comment by ALISONTS99** [comment]
Eu utilizo esse método do vídeo pra assistir na tv, não sei se você já conhece, da pra quebrar um galho.

https://user-images.githubusercontent.com/109309895/180089981-10b48839-2b34-488b-a0a3-43d822c788ea.mp4

.

**Comment by Mateus7G** [comment]
isso me deu uma boa ideia, aparentemente é possível abrir o webvideocaster direto por um schema deles no android 
```
wvc-x-callback://open?url=<url>
```
https://www.webvideocaster.com/integrations
qnd eu tiver um tempo sobrando vou ver se consigo adicionar um botão pra ir pro app direto

**Comment by ALISONTS99** [comment]
@Mateus7G Boa, se der certo vai facilitar bastante.

**Comment by ALISONTS99** [comment]
@Mateus7G Tava tentado usar a funcionalidade nova do web caster mas tá dando esse erro, sabe o que pode ser ?
![Screenshot_2022-07-23-14-11-32-444_com kiwibrowser browser](https://user-images.githubusercontent.com/109309895/180615647-cd483099-1872-4771-861a-17dc1b647920.jpg)

**Comment by Mateus7G** [comment]
@ALISONTS99 estou tentando resolver isso agora com base no https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/156 :/
subi a extensão achando q ia pegar já q funcionou no pc mas qnd testei no kiwi tbm deu esse problema

**Comment by Mateus7G** [comment]
@ALISONTS99 acabei de reupar as extensões aqui na mesma versão https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.2.1
não mudei o numero da versão mas houve uma mudança no c39fdffbbaa04b667b90189311d983f256963b55 que faltava pra permitir os links `wvc-x-callback://`

Tenta baixar dnv e testar o botão, aqui agora ta funcionando legal:

<img height="600px" src="https://user-images.githubusercontent.com/13335925/180621177-4bc5adcc-869b-4553-9f61-f086f166a2ae.png"/>

Como essa opção serve de alternativa pro chromecast que era o objetivo inicial da issue, vou fechar ela por aqui, obrigado pelas sugestões :+1:

**Comment by ALISONTS99** [comment]
@Mateus7G Teste e deu certo aqui tambem, valeu pelo trampo. Voce comentou que funciona no pc tambem, como faz pq nao achei o webvideocast pra baixar no pc

**Comment by Mateus7G** [comment]
infelizmente não tem pra pc não, eu quis dizer que testei se o protocolo `wvc-x-callback://` funcionava:

![image](https://user-images.githubusercontent.com/13335925/180622780-32480498-642d-403b-9ce5-d6020654111f.png)

no pc deu de boa mas no kiwi que tinha dado aquele "Navigation is blocked" (incrivelmente traduzido para "A Navegação GPS está bloqueada") q vc mandou

**Comment by ALISONTS99** [comment]
@Mateus7G Ah sim entendi, obrigado pela explicação, bom fim de semana pra você.

**Comment by ALISONTS99** [comment]
@Mateus7G nao tinha notado naquele dia, mas parece que botao pro webvideocaster funciona no site beta ne

**Comment by Mateus7G** [comment]
@ALISONTS99 ainda não testei mas sim, deveria funcionar

**Comment by ALISONTS99** [comment]
@Mateus7G eu digitei errado, na verdade eu queria dizer que nao funciona
![photo_5125504492786264686_y](https://user-images.githubusercontent.com/109309895/181830389-01969e13-204c-4876-ba0c-0dd013747f53.jpg)
.

**Comment by Mateus7G** [comment]
hmmm ook vou dar uma olhada

**Comment by Mateus7G** [comment]
@ALISONTS99 pode verificar se o problema foi corrigido na [v1.2.2](https://github.com/Mateus7G/crp-iframe-player/releases/latest)? :)

**Comment by ALISONTS99** [comment]
@Mateus7G  aqui funcionou legal
