### ISSUE TITLE
No cargan los episodios en crunchyroll beta

### ISSUE THREAD

**Issue by lcofer112** [Mateus7G/crp-iframe-player#47]
tengo la nueva actualizacion puesta pero los videos en el crunchyroll beta no cargan :(

**Comment by Mateus7G** [comment]
imagino que deve ser algo relacionado com o locale (#32) ja que em pt-br está funcionando normalmente, vou atualizar o player amanhã para tentar resolver esse problema, por hora, pode me informar se consegue assistir com as legendas em espanhol definindo o cookie manualmente para esES?

![image](https://user-images.githubusercontent.com/13335925/177449441-26fab32c-a9cb-4505-bff4-5381ac3d227e.png)
