### ISSUE TITLE
Vídeo em .mkv com legendas em todos os idiomas

### ISSUE THREAD

**Issue by SparkProyerT** [Mateus7G/crp-iframe-player#48]
Seria bom se o formato de vídeo baixado viesse em .mkv com todas as legendas de idioma dentro para que você pudesse alterar o idioma dentro do vídeo.

**Comment by Mateus7G** [comment]
A ideia é realmente boa mas tem algumas implicações que me impedem de querer gastar muito tempo nisso:
- Por algum motivo a formatação que vem embutida na legenda webvtt está sendo ignorada pelo jwplayer
- Não me dediquei muito a procurar mas apenas consegui encontrar a stream dos .vtt das legendas em ingles as outras estavam todas em hardsub, tbm não tentei encontrar as legendas pros eps premium pois vai dar mais trabalho ainda:

"multitrack_adaptive_hls_v2"             |  "adaptive_hls" (hardsub)
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/13335925/177551846-a6cde3e7-7775-425a-8ea5-da1c3d2d964d.png) | ![image](https://user-images.githubusercontent.com/13335925/177552202-6b7e02a5-a80d-4437-8a2a-ff3afc360b92.png)


---------

se quiser brincar com isso e ver se consegue manter a estilização aqui está um código que pode usar:

**playground.html**

```html
<div id="myElement"></div>

<script src="../assets/js/jwplayer.js"></script> <- esse aqui é o min do jwplayer.js que está no projeto
<script type="text/JavaScript">
    jwplayer("myElement").setup({ 
        "playlist": [{
            "file": "<url da stream aqui>",
            "preload": "metadata",
            
        }],
        "width": "50%",
        "height": "50%",
        "displayPlaybackLabel": true,
        "primary": "html5"
    });
</script>
```

Aqui ta a url de uma source com legenda embutida (talvez expire com o tempo, recomendo pegar da streamlist de um ep free p/ testar):
```
"https://pl.crunchyroll.com/evs3/574ecbf32ab797d203c75a32d650540d/assets/d293694f8277f8029f62f0b3d1c496ed_,3820195.mp4,3820196.mp4,3820194.mp4,3820192.mp4,3820193.mp4,225972.txt,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy81NzRlY2JmMzJhYjc5N2QyMDNjNzVhMzJkNjUwNTQwZC9hc3NldHMvZDI5MzY5NGY4Mjc3ZjgwMjlmNjJmMGIzZDFjNDk2ZWRfLDM4MjAxOTUubXA0LDM4MjAxOTYubXA0LDM4MjAxOTQubXA0LDM4MjAxOTIubXA0LDM4MjAxOTMubXA0LDIyNTk3Mi50eHQsLnVybHNldC9tYXN0ZXIubTN1OCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1NzI3OTcwN319fV19&Signature=ga2U8eawWR20shvzm1OXJyThCsfVr~QKmJGKpCYMODjGKqA6leqy4UTCzztBmIE4nT4YDnfmNI63m13-0p~kqMEfB0VjvfsbfvTxdUzRVZ1yWjOo7UdkoAzZWMQxyunvf0AiQbZk~LuAasMnp~3MLVwMwrNCbgjpe-aSJCsAhyZdxhiLY1rhmRAa1Kjp7rCJfO4IJ7YtUDC8ROqEwnLTsNp77W8ofV-6S3MRvpf4cCdfAf2tN9liWmVjXcEiKEecT17noQi6rMTCZRIWGG~dEtOBJRnMgITtZ7wHLUdAs1epXoTJPGxJowK~2T8ybm8hx~NiWcfqpL1WF377rNLtpg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"
```

Tbm tentei abrir esse m3u8 e colocar a legenda em um [`"track"` com o type: `"caption"`](https://developer.jwplayer.com/jwplayer/docs/jw8-add-captions#side-loaded-captions) como recomenda a doc do jwplayer, mas os estilos tbm não são mantidos

**Comment by Mateus7G** [comment]
Pra não descartar sua sugestão eu alterei o código do player na a6db63ccbf5fc030646ee7a00ccf588a3601fdff com "tracks falsas", quando o usuário mudar de caption na vdd ele vai tocar outro mp4/m3u8 com a hardsub que ele escolheu.
Agora, em vez de usar a stream que tem a lang do usuário o player salva todas as streams, isso talvez deixe um pouco mais lento nos eps que fazem request + blob mas espero que não custe tanto assim

(não é preciso atualizar a extensão, apenas atualizar a página limpano o cache, Ctrl + atualizar)
