### ISSUE TITLE
Não está pegando o Portugues

### ISSUE THREAD

**Issue by luannbr** [Mateus7G/crp-iframe-player#49]
Apos o update apareceo CC pra selecionar as legendas, ok, mas notei pelo menos em alguns projetos não está aparecendo o Portugues.

![Screenshot_2299](https://user-images.githubusercontent.com/18580842/177667704-ae0b1117-ffed-4e36-ba3d-357b49330d3e.jpg)

Até o momento deste post aqui nao aparece 
https://www.crunchyroll.com/pt-br/my-stepmoms-daughter-is-my-ex/episode-1-the-former-couple-refuses-to-say-852609
https://www.crunchyroll.com/pt-br/harem-in-the-labyrinth-of-another-world/episode-1-encounter-852622

**Comment by Mateus7G** [comment]
Esses episódios foram lançados ontem (no dia que você criou essa issue), e
por isso a crunchyroll ainda não tinha subido as legendas em português, por
favor verifique novamente.
