### ISSUE TITLE
Alguns capítulos de Naruto não são reproduzidos (Código de erro: 232011)

### ISSUE THREAD

**Issue by Edushii** [Mateus7G/crp-iframe-player#50]
Quase todos os capítulos de Naruto kid não são reproduzidos e as primeiras temporadas de Naruto Shippuden apresentam problemas com a ordem das qualidades do vídeo.

**Comment by Mateus7G** [comment]
vou investigar o problema do Naruto Shippuden, mas poderia informar algum ep do naruto que está dando esse código de erro?
abri alguns aqui e esta funcionando normalmente

![image](https://user-images.githubusercontent.com/13335925/180069934-dc53e08e-bcb3-4649-8785-a87eb70996a4.png)
- https://www.crunchyroll.com/pt-br/naruto/episode-43-killer-kunoichi-and-a-shaky-shikamaru-520366

**Comment by Flynston** [comment]
Não é só em Naruto, a extensão não está mais funcionando como relatado por outras pessoas aqui: https://greasyfork.org/pt-BR/scripts/411391-crunchyroll-iframe-player/feedback
![Screenshot_1](https://user-images.githubusercontent.com/109812184/180468294-76ed6759-6057-4d30-bf55-f52eafd47927.png)

**Comment by Mateus7G** [comment]
Imagino que o problema deve ser de CORS ao acessar os sites da vrv, antigamente a extensão contornava isso com um [proxy](https://github.com/Mateus7G/allOrigins) (lento), que foi corrigido da v1.1.0+ pra cima (na v1.1.0 usando o [background.js](https://github.com/Mateus7G/crp-iframe-player/commit/432daadb7ff94f2a1450213981f6ea792e17e39a#diff-3afe4d713f45080ca33675b8be73893c74a9b5b7565ed5fb50723c2eac932c64) e agora na v1.2.0 usamos as [regras da extensão](https://github.com/Mateus7G/crp-iframe-player/commit/6bb6ce3be09e1c1b1415b03e9ae62ba243579c00#diff-62f806cb9996318531c4ea037620933c0dbf5f2a041c9ea608461b613a0e091c)) pra evitar esse problema sem deixar o player lento.

> a extensão não está mais funcionando como relatado por outras pessoas aqui

Eu não sou o dono do script p/ tampermonkey, mas imagino que as pessoas que o usam estão tendo esse problema.

Até mesmo Overlord está funcionando de boa aqui:



Para resolver, faça o download da ultima versão: https://github.com/Mateus7G/crp-iframe-player/releases/tag/latest

**Comment by Mateus7G** [comment]
Caso esteja usando o script do tampermonkey, adicionei na 7956d3d7827aed9082bb065cb8eb7b3dbf52ca86 o proxy de volta, porém será necessário colocar `"tampermonkey": true` nas mensagens enviadas ao player.

-----

Infelizmente os eps de Naruto Shippuden estão fora de ordem na streamlist mesmo, e isso vem da crunchyroll... como não temos acesso ao m3u8 dos eps premium não é possível colocar na ordem correta como o player deles faz, também não tem nenhum campo na streamlist que eu possa usar pra identificar a qualidade, nem mesmo as URLs vem com essa informação, elas tem apenas os numeros `_xxxxxxx.mp4` que também infelizmente não está ordenado...

![image](https://user-images.githubusercontent.com/13335925/180576540-1c35410c-2a33-4669-8124-999ffb4a624f.png)

**Comment by Edushii** [comment]
Então não há solução?

**Comment by Mateus7G** [comment]
> Então não há solução?

Para ordenar os EPs de Naruto Shippuden, não.

Mas para assistir os outros animes basta atualizar a extensão para [v1.2.0](https://github.com/Mateus7G/crp-iframe-player/releases/tag/latest) ou se estiver pelo Tampermonkey colocar um `'tampermonkey': true` no script, assim: [greasyfork#142287](https://greasyfork.org/pt-BR/scripts/411391-crunchyroll-iframe-player/discussions/142287).

**Comment by Edushii** [comment]
Mas todos os capítulos do Naruto estão fora de ordem? Será isso um problema
da plataforma ou da extensão? A propósito, passe-me o seu WhatsApp para que
eu possa obter apoio técnico directamente daí, por favor, obrigado.

**Comment by Mateus7G** [comment]
Sim, isso é de fato um problema da ordenação da lista de streams da Crunchyroll.
A maioria dos animes vem na ordem 720p, 1080p, 480p, 360p e 240p. (inclusive abri um da 17 temporada e estava nessa ordem)

Desculpe, não pretendo ceder informações pessoais pelo GitHub.
