### ISSUE TITLE
Problema de reprodução no modo anônimo (Chrome)

### ISSUE THREAD

**Issue by K4nek0** [Mateus7G/crp-iframe-player#51]
Quando a extensão é ativada no modo anônimo, está apresentando loading infinito.

**Comment by Mateus7G** [comment]
isso acontece pq a extensão usa cookies, e seu navegador provavelmente está definido para bloquear cookies de terceiros em guias anonimas.

pra resolver isso você pode ir em `chrome://settings/cookies` e escolher entre:
1. ativar cookies apenas para o site do player (recomendado):

![image](https://user-images.githubusercontent.com/13335925/180067210-f7d0e609-79c9-4576-82f8-f2e72083b8ca.png)

2. ativar cookies (para todos os sites) incluindo guias anonimas:

![image](https://user-images.githubusercontent.com/13335925/180067081-0a775a73-b5f3-4ec4-a6c9-2c52e6d40b68.png)

como isso é um bug q eu não conhecia, vou ver de fazer depois um warning se o navegador do usuario esta com os cookies desativados nesses casos, obg pela issue :+1:

**Comment by K4nek0** [comment]
Problema resolvido. Eu que agradeço pela ajuda 👍
