### ISSUE TITLE
Animes com restrição de idade não reproduzem na Crunchyroll Beta

### ISSUE THREAD

**Issue by HitaloSama** [Mateus7G/crp-iframe-player#54]
Estou tentando assistir Attack on Titan e mesmo episódios que não precisam de premium ficam carregando infinitamente.
Eu não sei ao certo como lhe enviar os logs, se precisar me mande as instruções que farei. xD

![image](https://user-images.githubusercontent.com/40531911/180481858-85f8bfea-3ac4-4f06-adbe-81f20c5c8477.png)

**Comment by Mateus7G** [comment]
Como pode ter lido no [:memo: Aviso Crunchyroll Beta](https://github.com/Mateus7G/crp-iframe-player#-aviso-crunchyroll-beta), a versão da CR Beta usa a versão antiga do Crunchyroll pra pegar os vídeos, e oq ta acontecendo é que ao entrar na versão antiga a extensão está se deparando com isso:

![image](https://user-images.githubusercontent.com/13335925/180510107-9ac79864-5f08-4d18-bc18-88df9a9e700c.png)

Pra resolver acho que é só botar um `?skip_wall=1` no código na hora de buildar a URL, vou fazer isso jajá

![image](https://user-images.githubusercontent.com/13335925/180510497-43b5ec15-ae73-436e-954b-038249137b4a.png)

**Comment by Mateus7G** [comment]
Corrigido: 8d41f82afd953462ed7ba5e3d1d9224ae691092b. Espera uns minutinhos e da um F5 resetando o cache que já deve voltar a funcionar

**Comment by HitaloSama** [comment]
> Corrigido: [8d41f82](https://github.com/Mateus7G/crp-iframe-player/commit/8d41f82afd953462ed7ba5e3d1d9224ae691092b). Espera uns minutinhos e da um F5 limpa o cache que já deve voltar a funcionar, obrigado pela issue! 👍

Excelente e de nada. xD

**Comment by HitaloSama** [comment]
@Mateus7G só mais um detalhe; quando eu clico no "próximo episódio" a página é atualizado menos o player, que se mantem com o episódio anterior.
