### ISSUE TITLE
Mudar de episódio não atualiza o player no Crunchyroll Beta

### ISSUE THREAD

**Issue by Mateus7G** [Mateus7G/crp-iframe-player#55]
> @Mateus7G só mais um detalhe; quando eu clico no "próximo episódio" a página é atualizada, menos o player, que se mantem com o episódio anterior.

[](https://user-images.githubusercontent.com/40531911/180578022-10672d0e-a5b0-425c-9f09-16920faa29ba.mp4)

_Originally posted by @HitaloSama in https://github.com/Mateus7G/crp-iframe-player/issues/54#issuecomment-1192987883_

**Comment by Mateus7G** [comment]
@HitaloSama vou investigar em breve assim que eu conseguir

**Comment by Mateus7G** [comment]
@HitaloSama corrigido na nova versão [v1.2.1](https://github.com/Mateus7G/crp-iframe-player/releases/tag/v1.2.1) :+1:

**Comment by mrpandix** [comment]
![image](https://user-images.githubusercontent.com/97079235/183992799-a1c69967-1398-4586-bb4a-58bb307617ac.png)
não pode mais jogar o episódio é completamente preto
