### ISSUE TITLE
popup.js:29 (setValue)

### ISSUE THREAD

**Issue by Likaluz** [Mateus7G/crp-iframe-player#57]
![image](https://user-images.githubusercontent.com/110208263/181660308-c99406c5-85d9-46a0-9ebf-ded695a95fc2.png)
esta dando esse erro aqui

**Comment by Mateus7G** [comment]
hmmm bem observado, enquanto não lanço um update para corrigir vc pode apagar esse erro ali na lixeira e colocar os valores do popup da extensão novamente que deve salvar normalmente

**Comment by Nehnoia12** [comment]
![Capturar](https://user-images.githubusercontent.com/110293788/181917486-1fb9640e-93dc-4f8b-92ed-80ca4b555f19.PNG)

o meu da esse erro, sabe como arrumar? obrigado

**Comment by Mateus7G** [comment]
@Nehnoia12 seu erro não é o mesmo do tópico acima, mas ja adianto que provavelmente você está em uma versão desatualizada da extensão.
Por favor [atualize para a última versão](https://github.com/Mateus7G/crp-iframe-player/releases/tag/latest) e se o problema persistir crie uma nova issue.

**Comment by Mateus7G** [comment]
@Likaluz corrigido na [v1.2.2](https://github.com/Mateus7G/crp-iframe-player/releases/latest)
