### ISSUE TITLE
Erro Codigo 232011

### ISSUE THREAD

**Issue by TheDragonsFlame** [Mateus7G/crp-iframe-player#60]
Erro aparece em todos os vídeos

"Erro ao carregar o vídeo! (>﹏<) Mais informações no Console. Código: 232011

**Comment by Mateus7G** [comment]
O player está funcionando normalmente **na última versão**. Provavelmente você ainda não atualizou.  
Atualize a extensão para a última versão, e, caso o erro persista, volte aqui, reabra a issue e dê mais informações:
- A versão do crunchyroll (CR Antigo / CR Beta).
- A versão da extensão que está usando (`chrome://extensions`).
- Seu navegador (chrome/opera/kiwi).
- Logs do Console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> +<kbd>J</kbd>).

![image](https://user-images.githubusercontent.com/13335925/183245249-8d897e6b-b6e0-4f84-a148-3beeb8a50acb.png)

**Comment by TheDragonsFlame** [comment]
Desculpas, estou no firefox. A tentativa de atualização exibe a mensagem "Nenhuma atualização encontrada"

**Comment by Mateus7G** [comment]
@TheDragonsFlame perdão, a extensão desse repositório suporta apenas navegadores baseados em chromium https://github.com/Mateus7G/crp-iframe-player/issues/38
Porém você pode baixar a versão mais recente (1.2.2) para firefox no [repositório do Rgern100](https://github.com/Rgern100/crp-iframe-player-Firefox):

https://github.com/Rgern100/crp-iframe-player-Firefox/releases/latest
