### ISSUE TITLE
Erro ao tentar assistir Charlotte, anime da Crunchyroll com a extensão 

### ISSUE THREAD

**Issue by Jonasshow** [Mateus7G/crp-iframe-player#61]
## Descrição 
Erro ao carregar o vídeo! (>﹏<)
Mais informações no Console.
[Código: 232011]

## Link
(https://www.crunchyroll.com/pt-br/charlotte/episode-1-i-think-about-others-682165)

## Informações Adicionais
[CR Premium] Player encontrado!
player.js:26 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at player.js:26:48

**Comment by Mateus7G** [comment]
Hmm esse episódio ta funcionando normalmente por aqui (tanto deslogado quanto no beta)...

![image](https://user-images.githubusercontent.com/13335925/183538511-8af8622d-64f7-4ba2-aeac-20f8852c046b.png)

Já que não consegui reproduzir, tente reinstalar a extensão na [última versão](https://github.com/Mateus7G/crp-iframe-player/releases/latest) e veja se o problema ainda persiste

**Comment by Jonasshow** [comment]
Agora funcionou certinho com essa versão mais atualizada, muito obrigado, você é muito bom.
