### ISSUE TITLE
Problema em jogar qualquer anime.

### ISSUE THREAD

**Issue by NaxiithoxxD** [Mateus7G/crp-iframe-player#62]
Olá, estou aqui para ver se sou o único com o problema, quando estava assistindo um anime, cerca de 1 hora atrás, o player parou de funcionar, o botão play não apareceu e o vídeo parou de aparecer no da mesma forma, mudei o anime e o navegador, fui para o github, foi lá que baixei a última versão e finalmente reiniciei o computador, mas nenhuma dessas coisas funciono.

(navegador onde tentei foram: Microsoft Edge e Google Chrome).

vídeo onde você pode ver que não funciona:

https://user-images.githubusercontent.com/111016278/184011087-d9efe6e2-9b7a-4d68-999c-76c2a6a4d9ec.mp4

**Comment by BFRC-UPCH** [comment]
Same thing, tried even cleaning all data and a new install. Opera GX and Chrome

**Comment by OnlyDiniz** [comment]
Estou com o mesmo problema...
![image](https://user-images.githubusercontent.com/108842720/184025831-af2fee2e-2b67-44dc-86a4-2bc7b7f8af1a.png)

**Comment by mrpandix** [comment]
I also have the same problem :'(

**Comment by Dachnilo** [comment]
I think Crunchyroll did something, It also no longer works with the Kiwi browser, and the older versions no longer work either

**Comment by NedcloarBR** [comment]
Ae galera pelo que testei aqui esse erro só ocorre no site Beta tentem ir pro site normal(fazendo logout da conta) e tentem novamente olhar o anime

Hey guys for what I tested here this error only occurs on the Beta site try to go to the normal site (logging out of the account) and try again to watch the anime

**Comment by Mateus7G** [comment]
A crunchyroll mexeu na API beta deles e quebrou a extensão, enquanto eu arrumo por favor faça o que o @NedcloarBR recomendou: deslogue (ou entre em guia anonima) para assistir e assim que corrigir vou notificar aqui com a atualização

**Comment by danibele** [comment]
![image](https://user-images.githubusercontent.com/111033624/184058760-865dbb74-abd6-45b6-bf04-da9c31eedc5b.png)
 
A unica forma agora e deslogando.
log out then try again without log in back.

**Comment by Mateus7G** [comment]
Problema corrigido na [v1.3.0](https://github.com/Mateus7G/crp-iframe-player/releases/latest)
