### ISSUE TITLE
Modo escuro no site

### ISSUE THREAD

**Issue by NedcloarBR** [Mateus7G/crp-iframe-player#63]
Salve Mateus tranquilo?
então mano se conseguir dar uma força pra gente e integrar na extensão um modo noturno pro site da Crunchyroll meus olhos e acredito que de muitas outras pessoas agradecem ksks

achei essa extensão [aqui](https://chrome.google.com/webstore/detail/dark-skin-for-crunchyroll/agjiicokbioponboibkfhfgmhcacafph) no WebStore do Chrome mas não quis baixar ela pra não ficar 2 extensões pesando no navegador saca?
ela tá nesse repo [aqui](https://github.com/tholinka/Dark-Crunchyroll-Plugin) 

se conseguir dar uma olhada e quem sabe aplicar na extensão agradeço muito mesmo!

**Comment by Mateus7G** [comment]
customizar o layout do site é uma ideia bem bacana, mas acho melhor não trazer essa funcionalidade de dark mode pra extensão unicamente pelo fato de que é possível que a qualquer momento a CR pode remover o layout antigo :(
