### ISSUE TITLE
Quando eu tento dar play em algum anime, o player fica escuro.

### ISSUE THREAD

**Issue by Ironpeu** [Mateus7G/crp-iframe-player#65]
![imagem_2022-08-11_134713593](https://user-images.githubusercontent.com/98492408/184189150-bab16baa-0170-47f0-88d8-2a6fcc0d7c17.png)
## Descrição
quando clico no anime que quero ver, ele até carrega a página, mas não chega à carregar o player do vídeo/episódio

## Link
Acontece com qualquer série da crunchyroll

## Informações Adicionais
Opéra GX, navegador que uso atualmente

**Comment by Dachnilo** [comment]
It's difficult at the moment, it's best to log out and continue looking on the normal page (no BETA)
without signing up.

É difícil no momento, é melhor sair e continuar procurando na página normal (sem BETA)
sem se inscrever.

**Comment by NedcloarBR** [comment]
de uma olhada no #62

take a look at #62
