### ISSUE TITLE
problema com a versão beta

### ISSUE THREAD

**Issue by StarGuardianMukuro** [Mateus7G/crp-iframe-player#66]
Estou com um problema com o player na versão beta, ele fica em uma tela preta e não mostra o vídeo, espero que resolvam esse problema pois afeta até conteúdo não premium

**Comment by Jooj000** [comment]
desloga da conta e usa a versão antiga até arrumarem, a crunchyroll beta quebrou a extensão dnv

**Comment by StarGuardianMukuro** [comment]
Eu concordo e espero que eles tenham uma solução em breve

**Comment by Slowayy** [comment]
> Eu concordo e espero que eles tenham uma solução em breve

mas acho que a extensão vai de berço, até acharem uma nova forma de puxar os dados do anime, tão fazendo com que as contas betas não tenham como voltar atrás para o normal, e se tão fazendo isso é provavelmente pra acostumar os usuários e excluir a parte antiga do site

**Comment by StarGuardianMukuro** [comment]
Não, o problema que tenho é que quando estou na versão beta do crunchyrrol ele só me mostra uma tela preta quando jogo um episódio do anime

**Comment by StarGuardianMukuro** [comment]
ontem de manhã eles trabalham em 100, mas à tarde só me mostrou uma tela preta

**Comment by darkkaos** [comment]
> > Eu concordo e espero que eles tenham uma solução em breve
> 
> mas acho que a extensão vai de berço, até acharem uma nova forma de puxar os dados do anime, tão fazendo com que as contas betas não tenham como voltar atrás para o normal, e se tão fazendo isso é provavelmente pra acostumar os usuários e excluir a parte antiga do site

Visto a resposta do criador do mod, muito provavelmente vai ir de base quando a crunchy retirar completamente o site antigo, já que não tem mais os trailers.
Vai ser uma grande perda >.<

**Comment by NedcloarBR** [comment]
de uma olhada no #62

take a look at #62

**Comment by Mateus7G** [comment]
pois é @darkkaos, mas enquanto a versão antiga ainda ta por ai ainda da pra puxar os dados... corrigido na #62
