### ISSUE TITLE
problema ao jogar um anime em particular Valkyrie Drive -Mermaid-

### ISSUE THREAD

**Issue by StarGuardianMukuro** [Mateus7G/crp-iframe-player#68]
eu vi que você acabou de corrigir o problema beta do crunchyroll
Eu realmente aprecio isso, mas desde a versão anterior há um problema com este anime Valkyrie Drive -Mermaid-
Não roda e fica carregando e já aconteceu com alguns outros animes 
talvez seja porque eles são animes +18?

**Comment by Mateus7G** [comment]
hmmm o problema na verdade é que a extensão está procurando por

```
https://www.crunchyroll.com/pt-br/valkyrie-drive--mermaid-/episode-774109
```
quando na verdade o link correto é

```
https://www.crunchyroll.com/pt-br/valkyrie-drive-mermaid-/episode-774109
```

espere um pouco

**Comment by StarGuardianMukuro** [comment]
Ok vou tentar esperar e ver se
jogar o episódio ou não

**Comment by Mateus7G** [comment]
Aqui está funcionando agora, limpa o cache do navegador e atualiza a página que já deve voltar a funcionar (espero não ter quebrado outros animes que tinham `--` com esse fix :fearful:)

![image](https://user-images.githubusercontent.com/13335925/184464717-f3c2ffc8-b6d1-4b56-bde4-139d6c2f668a.png)

**Comment by StarGuardianMukuro** [comment]
agora funcionou muito obrigado

eu tive o problema
com outros animes com mais de 18 anos e estava carregando apenas por vários minutos qualquer problema eu acho que posso denunciá-lo se você quiser
