### ISSUE TITLE
Error 503 Response object too large

### ISSUE THREAD

**Issue by dragonmoe** [Mateus7G/crp-iframe-player#71]
Saga of Tanya the Evil: the Movie
1080p : [link](https://fy.v.vrv.co/evs3/554b79633b6c41bc4d1b5466fad720e2/assets/3cad2586d6269433718782c98efc15c6_3719171.mp4) 
Fullmetal Alchemist: The Conqueror of Shamballa
1080p : [link](https://fy.v.vrv.co/evs3/c52f4f4c7b0e4474b6a942185eb32718/assets/il5xzf2bcfn3dn5_2919623.mp4)

**Comment by Mateus7G** [comment]
@hippomu-media Esse é um limite da própria VRV que não posso corrigir, é possível assistir por stream mas baixar o mp4 bruto não funcina, veja #45
