### ISSUE TITLE
Problemas com carregamento

### ISSUE THREAD

**Issue by xrcsray** [Mateus7G/crp-iframe-player#8]
po cara agredeço demais o seu trabalho pela comunidade fã de anime mas eu percebi que quando eu uso a extensão o vídeo trava o tempo todo no pc como se fosse problema de internet. não sei se é só comigo, pra testar desativei a extensão e usei um adblock normal e os problemas de demora pra carregar e travamento sumiram.

**Comment by augusttex** [comment]
> po cara agredeço demais o seu trabalho pela comunidade fã de anime mas eu percebi que quando eu uso a extensão o vídeo trava o tempo todo no pc como se fosse problema de internet. não sei se é só comigo, pra testar desativei a extensão e usei um adblock normal e os problemas de demora pra carregar e travamento sumiram.

opa irmão, n sou o criador, mas pra resolver isso eu inicio o ep dou uma puladinha e dou reload na pagina, o ep volta liso e sem travar. De primeira as vezes n da, vai tentando q acaba indo

**Comment by Mateus7G** [comment]
provavelmente os que tão demorando são os eps premium que tão teno que carregar o .mp4 inteiro já q nao consegui encontar um link pro .m3u8 deles direto... infelizmente nao vo te tempo pra caçar onde eles estão, mas se alguem encontrar ou quiser subir uma PR pode ficar a vontade :+1: 
vou deixar essa issue aberta

**Comment by xinigamir** [comment]
aqui também começou a ter problemas de carregamento, carrega um pouco e para e se colocar no automático vai ficar uma qualidade bem baixa

**Comment by Pinoia0** [comment]
Eu criei uma conta gratuita para maior de idade na Crunchyroll pra assistir animes sem censura e usei a extensão, mesmo o episódio não sendo premium o play não carregam[https://www.crunchyroll.com/pt-br/maken-ki/episode-1-the-day-we-swore-to-heaven-737163](url)

**Comment by Mateus7G** [comment]
Atualizei a extensão para diminuir o tempo de carregamento da stream
nota: nos eps premium ainda não é possível assistir pelo m3u8, apenas por mp4, porém já não é mais necessário baixar o conteúdo previamente para assistir
